const messages = {
  gender: {
    MALE: "Male",
    FEMALE: "Female",
    OTHER: "Other"
  },
  pushNotification: {
    EMAIL: "Email",
    SMS: "SMS",
    PUSH: "Push Notification"
  },
  paymentMethod: {
    DIRECT_DEPOSIT: "Direct Deposit",
    PAY_CHEQUE: "Pay Cheque",
    OTHER: "Other"
  },
  onlineStatus: {
    AVAILABLE: "Available",
    OUT_OF_OFFICE: "Out of office",
    IN_A_MEETING: "In a meeting",
    AWAY: "Away",
    BUSY: "Busy",
    DO_NOT_DISTURB: "Do not disturb",
    BE_RIGHT_BACK: "Be right back",
    OFFLINE: "Offline"
  },
  modalTitles: {
    assignPosition: "Assign Position",
    assignStatus: "Assign Status"
  },
  relationStatus: {
    MARRIED: "Married",
    SINGLE: "Single",
    SINGLE_PARENT: "Single Parent",
    UNKNOWN: "Unknown",
    OTHER: "Other"
  },
  paymentType: {
    HOURLY: "Hourly",
    SALARY: "Salary",
    OTHER: "Other"
  },
  statusEnum: {
    PENDING1: "Pending 1",
    PENDING2: "Pending 2",
    APPROVED: "Approved",
    REJECTED: "Rejected"
  },
  degree: {
    BACHELOR: "Bachelor",
    COLLEGE: "College",
    MASTER: "Master",
    PHD: "PhD",
    PRIMARY: "Primary",
    SECONDARY: "Secondary",
    TRADE_SCHOOL: "Trade School"
  },
  general: {
    years: "years",
    duedate: "Due Date",
    issueDate: "Issue Date",
    yearsOld: "years old",
    empID: "Employee ID",
    attachments: "Attachments",
    properties: "Properties",
    type: "Type",
    employmentType: "Employment Type",
    employer: "Employer",
    active: "Active",
    empStatus: "Employee Status",
    effectiveDate: "Effective Date",
    expiryDate: "Expiry Date",
    approvedOn: "Approved On",
    approvedBy: "Approved By",
    asof: "as of",
    general: "General",
    position: "Position",
    additionalproperties: "Additional Properties",
    ok: "Ok",
    reset: "Reset",
    order: "Order",
    actions: "Actions",
    allemp: "All Employees",
    delete: "Delete",
    cancel: "Cancel",
    bulkactions: "Bulk Actions",
    bulkdelete: "Bulk Delete",
    invalidvalueerror: "Invalid value",
    duplicatenameerror: "Duplicate name error",
    home: "Home",
    dataadded: "Data added",
    datadeleted: "Data deleted",
    dataupdated: "Data updated",
    Compensation: "Compensation",
    reloadpage: "Reload",
    noData: "No data",
    success: "Success",
    areYouSure: "Are you sure?",
    confirmdelete: "Are you sure you want to delete this item?",
    failed: "Failed",
    servererror: "Server error. Please try again",
    somethingwentwrong: "Something went wrong",
    deleted: "Deleted",
    informationadded: "Information added",
    informationupdated: "Information updated",
    informationdeleted: "Information deleted",
    days: "Days",
    weeks: "Weeks",
    months: "Months",
    period: "Period",
    details: "Details",
    conditions: "Conditions",
    status: "Status",
    name: "Name",
    back: "Back",
    nofieldsaremodified: "No fields are modified",
    info: "Info",
    thisactionwilleffectassignedemployeesaswell:
      "This action will effect assigned employees as well",
    payitemassignmentstatuswillbeupdatedforallassignedemployees:
      "Pay item assignment status will be updated for all assigned employees",
    trackingitemsforthissegmentwillberemoved:
      "Tracking items for this segment will be removed",
    yes: "Yes",
    no: "No",
    selectGroupType: "Select Group Type",
    filterByGroup: "Filter By Group"
  },
  editProfile: {
    personalTab1: "Personal Email, Phone, Date of Birth and more",
    personalTab2: "Address, Postal Code, Country",
    personalTab3: "Bank Name, Account Number, Routing Number",
    personalTab4: "School, Degree, Major, GPA, Graduation Year",
    personalTab5: "ID Type, Number, Expiry Date",
    personalTab6: "Other Settings",
    nonResident: "Non-Resident",
    organizationProperties: "Organization Properties",
    bankAccounts: "Bank Accounts",
    idNumbers: "Other IDs",
    other: "Other",
    level: "Level",
    step: "Step",
    primary: "Primary",
    editProfile: "Edit Profile",
    benefitplan: "Benefit Plan",
    medicalAlert: "Medical Alert",
    addBenefitPlan: "Add Benefit Plan",
    assets: {
      assets: "Assets",
      returndate: "Return Date",
      assignasset: "Assign Asset",
      assignedassets: "Assigned Assets",
      overdue: "Overdue"
    },
    training: {
      training: "Training",
      addNewTraining: "Add New Training",
      status: "Status",
      completionDate: "Completion Date",
      evaluation: "Evaluation",
      signId: "Sign ID",
      note: "Note"
    },
    union: {
      union: "Union",
      addUnion: "Add Union"
    },
    skills: {
      skills: "Skills",
      proficiency: "Proficiency",
      experienceinyears: "Experience in years",
      experienceasoffdate: "Experience as off date"
    },
    licenseAndPermit: {
      licenseAndPermit: "License and Permit",
      id: "ID",
      addLicense: "Add License"
    },
    benefitOption: {
      benefitOption: "Benefit Option",
      idNumber: "ID",
      class: "Class",
      benefitStatus: "Benefit Status",
      claim: "Claim Dependents",
      overrideannualearnings: "Override Annual Earnings",
      overridedefaultcoverage: "Override Default Coverage",
      optoutmedical: "Opt-out Medical",
      optoutdental: "Opt-out Dental",
      optoutadnd: "Opt-out AD&D",
      optoutclinicalillness: "Opt-out Critical Illness",
      smoker: "Smoker",
      evidence: "Evidence",
      memberDescription: "Member Description"
    },
    benefitTableData: {
      memberDescription: "Member Description",
      name: "Name",
      option: "Option",
      ID: "ID",
      class: "Class",
      status: "Status",
      expiry: "Expiry"
    },
    unionTableData: {
      expiry: "Expiry",
      name: "Name",
      category: "Category",
      ID: "ID",
      region: "Region",
      sector: "Sector",
      tradeCode: "Trade Code",
      unionStatus: "Union Status",
      trade: "Trade",
      wage: "Wage"
    },
    skillsTableData: {
      proficiency: "Proficiency",
      experience: "Experience",
      addSkill: "Add Skill"
    },
    taxation: {
      taxation: "Taxation"
    }
  },
  countries: {
    // CA: 'Canada',
    CANADA: "Canada",
    // US: 'United States of America',
    USA: "United States of America"
  },
  warnings: {
    reportUse: "Use for reposts",
    datamodified: "",
    exitwithoutsave: "Do you wish to skip your changes?"
  },
  provinces: {
    CANADA: {
      AB: "Alberta",
      BC: "British Columbia",
      MB: "Manitoba",
      NB: "New Brunswick",
      NL: "Newfoundland & Labrador",
      NS: "Nova Scotia",
      NT: "Northwest Territories",
      NU: "Nunavut",
      ON: "Ontario",
      PE: "Prince Edward Island",
      QC: "Quebec",
      SK: "Saskatchewan",
      YT: "Yukon"
    },
    USA: {
      AL: "Alabama",
      AK: "Alaska",
      AZ: "Arizona",
      AR: "Arkansas",
      CA: "California",
      CO: "Colorado",
      CT: "Connecticut",
      DE: "Delaware",
      DC: "District Of Columbia",
      FL: "Florida",
      GA: "Georgia",
      HI: "Hawaii",
      ID: "Idaho",
      IL: "Illinois",
      IN: "Indiana",
      IA: "Iowa",
      KS: "Kansas",
      KY: "Kentucky",
      LA: "Louisiana",
      ME: "Maine",
      MD: "Maryland",
      MA: "Massachusetts",
      MI: "Michigan",
      MN: "Minnesota",
      MS: "Mississippi",
      MO: "Missouri",
      MT: "Montana",
      NE: "Nebraska",
      NV: "Nevada",
      NH: "New Hampshire",
      NJ: "New Jersey",
      NM: "New Mexico",
      NY: "New York",
      NC: "North Carolina",
      ND: "North Dakota",
      OH: "Ohio",
      OK: "Oklahoma",
      OR: "Oregon",
      PA: "Pennsylvania",
      RI: "Rhode Island",
      SC: "South Carolina",
      SD: "South Dakota",
      TN: "Tennessee",
      TX: "Texas",
      UT: "Utah",
      VT: "Vermont",
      VA: "Virginia",
      WA: "Washington",
      WV: "West Virginia",
      WI: "Wisconsin",
      WY: "Wyoming"
    }
  },
  relationships: {
    AUNT: "Aunt",
    BOYFRIEND: "Boyfriend",
    BROTHER: "Brother",
    "BROTHER-IN-LAW": "Brother-in-law",
    CONTACT: "Contact",
    DAUGHTER: "Daughter",
    "EX-HUSBAND": "Ex-Husband",
    "EX-WIFE": "Ex-Wife",
    FATHER: "Father",
    "FATHER-IN-LAW": "Father-in-law",
    FIANCE: "Fiance",
    FIANCEE: "Fiancee",
    FRIEND: "Friend",
    GIRLFRIEND: "Girlfriend",
    GRANDFATHER: "Grandfather",
    GRANDMOTHER: "Grandmother",
    HUSBAND: "Husband",
    MOTHER: "Mother",
    "MOTHER-IN-LAW": "Mother-in-law",
    NEIGHBOUR: "Neighbor",
    NEPHEW: "Nephew",
    NIECE: "Niece",
    PARTNER: "Partner",
    RELATIVE: "Relative",
    SISTER: "Sister",
    "SISTER-IN-LAW": "Sister-in-law",
    SON: "Son",
    SPOUSE: "Spouse",
    "STEP-DAUGHTER": "Step-daughter",
    "STEP-FATHER": "Step-father",
    "STEP-MOTHER": "Step-mother",
    "STEP-SON": "Step-son",
    UNCLE: "Uncle",
    UNKNOWN: "Unknown",
    WIFE: "Wife"
  },
  roles: {
    ORG_ADMIN: "Org Admin",
    EMPLOYEE: "Employee",
    SUPERVISOR: "Supervisor",
    SUPERVISORS: "Supervisors",
    PAY_MANAGER: "Pay Managers",
    HR_MANAGER: "HR Managers",
    SYS_ADMIN: "System Admin",
    MANAGERS: "Managers",
    MANAGER: "Manager"
  },
  dashboard: {
    dashboard: "Dashboard",
    editProfile: "Edit Profile",
    employees: "Employees",
    totalDocuments: "Total documents",
    teams: "Teams",
    attendancePolicies: "Attendance Policies",
    workPlan: "Work Plan",
    latestTimeOff: "Latest submitted time-off requests ",
    latestDoc: "Latest Document Dates",
    supervisor: "Supervisor",
    leftPanel: {
      availability: "Availability",
      code: "Code",
      badge: "Badge",
      cell: "Cell",
      work: "Work",
      email: "Email",
      groups: "Groups",
      lastlogin: "Last Login"
    }
  },
  buttons: {
    add: "Add",
    update: "Update",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    dontSave: "Dont Save",
    search: "Search",
    clear: "Clear",
    close: "Close",
    edit: "Edit",
    view: "View",
    addNew: "Add New",
    addNewEmployee: "Add a new Employee",
    columns: "Columns",
    assigntoemployees: "Assign Employees",
    modify: "Modify",
    export: "Export",
    upload: "Upload"
  },
  exitModal: {
    title: "You have unsaved changes.",
    description: "Do you wish to save your changes?"
  },
  profile: {
    terminationId: "Termination ID",
    basicInfo: {
      title: "Basic Info",
      firstName: "First Name",
      lastName: "Last Name",
      fullName: "Full Name",
      workEmail: "Work Email",
      personalEmail: "Personal Email",
      workPhone: "Work Phone",
      cellPhone: "Cell Phone",
      workcellphone: "Work Cell Phone",
      homePhone: "Home Phone",
      badgeNumber: "Badge Number",
      tempBadgeNumber: "Temporary Badge Number",
      employeeCode: "Employee Code",
      seniorityDate: "Seniority Date",
      secondaryseniorityDate: "Secondary Seniority Date",
      initiationDate: "Initiation Date",
      miscDate: "Misc Date",
      terminationDate: "Termination Date",
      changeProfilePicture: "Change your profile picture",
      groups: "Groups",
      sin: "Social insurance number (SIN)",
      birthDate: "Date of birth",
      email: "Email",
      hireInvitation: "Hire and send an email invitation",
      hireManually: "Hire and enter employee information manually",
      jobTitle: "Job Title",
      recordType: "Record Type",
      blockAccess: "Block Access",
      blockProfileChanges: "Block Profile Changes",
      empTemplateId: "Employee Template ID",
      middleName: "Middle Name",
      alias: "Nickname",
      nickname: "Nick Name",
      status: "Status",
      isRegistered: "Registered"
    },
    personal: {
      personal: "Personal",
      idNumbers: "ID Numbers",
      birthday: "Birthday",
      gender: "Gender",
      paymentMethod: "Payment Method",
      payStubs: "Pay Stubs",
      maritalStatus: "Marital status"
    },
    address: {
      title: "Address",
      address1: "Address Line 1",
      address2: "Address Line 2",
      city: "City",
      postalCode: "Postal Code",
      zipCode: "Zip Code",
      country: "Country",
      province: "Province",
      state: "State"
    },

    bankAccount: {
      title: "Bank Account",
      branch: "Branch Transit (5)",
      bank: "Bank ID (3)",
      accountNumber: "Account Number (7+)",
      chequeSpecimen: "Cheque Specimen"
    },
    paymentMethod: {
      title: "Payment Method"
    },
    education: {
      title: "Education",
      highestlevelofEducation: "Highest level of education",
      graduationDate: "Graduation Date",
      country: "Country",
      notes: "Notes"
    },
    idNumbers: {
      idType: "Type",
      idNumber: "Number",
      issuedCountry: "Issued Country"
    },
    nonResident: {
      title: "Non-Resident",
      alertDate: "Alert Date",
      visaExpiryDate: "Visa Expiry Date",
      passportExpiryDate: "Passport Expiry Date",
      statusReviewDate: "Status Review Date",
      passportNumber: "Passport Number",
      passportIssuingCountry: "Passport Issuing Country",
      status: "Status",
      visaNumber: "Visa Number",
      visaType: "Visa Type",
      note: "Note"
    },
    preferences: {
      employeeBirthDay: "Employee Birthday",
      newDocument: "New Document",
      newSchedule: "New Schedule",
      shiftEnd: "Shift End",
      shiftStart: "Shift Start",
      timeOffApproval: "Time Off Approval",
      timeOffComment: "Time Off Comment",
      timeOffRejection: "Time Off Rejection",
      timeOffSubmittal: "Time Off Submittal",
      timeSheetApproval: "Time Sheet Approval",
      timeSheetComment: "Time Sheet Comment",
      timeSheetRejection: "Time Sheet Rejection",
      timeSheetSubmittal: "Time Sheet Submittal"
    },
    custom: {
      title: "Custom"
    },
    contacts: {
      title: "Contacts",
      contactsAndFamily: "Contacts and Family",
      contact: "Contact",
      relationship: "Relationship",
      callSequence: "Emergency Call Sequence",
      note: "Note"
    },
    settings: {
      title: "Settings",
      preferences: "Preferences",
      preferredLanguage: "Preferred Language",
      preferredDateFormat: "Preferred Date Format",
      notifications: "Notifications",
      isTimeSheetApproval: "Time Sheet Approval",
      isTimeSheetRejection: "Time Sheet Rejection",
      isTimeSheetMessage: "Time Sheet Message",
      isTimeOffApproval: "Time Off Approval",
      isTimeOffRejection: "Time Off Rejection",
      isNewDocument: "New Document",
      asOfDate: "As of Date : "
    },
    payRate: {
      payRateAssign: "Pay Rate Assign",
      addPayRate: "Add Pay Rate",
      editPayRate: "Edit Pay Rate",
      payRateType: "Pay Rate Type",
      payRate: "Pay Rate",
      currency: "Currency",
      paymentMethod: "Payment Method",
      latestEffectiveDate: "Latest Effective Date"
    },
    compensation: {
      standardhoursperday: "Standard Hours Per Day",
      standardhoursperpay: "Standard Hours Per Pay",
      excludeattendancehoursfrompay: "Exclude Attendance Hours From Pay",
      secondaryPayRate: "Secondary Pay Rate",
      prevEmployment: "Previous Employment"
    },
    list: {
      bulkActions: "Bulk Actions",
      hire: "Hire",
      sendEmail: "Send Email",
      assignEmployeeToTheGroup: "Assign Employee to the Group",
      blockAccess: "Block Access",
      activeAccess: "Active Access",
      empsSelected: "employee(s) selected.",
      effectiveDate: "Effective Date",
      expiryDate: "Expiry Date",
      dateBasedGroups: "Date based groups",
      noExpiry: "No Expiry",
      filters: "Filters",
      resetColumns: "Reset Columns"
    }
  },
  audit: {
    property: "Property",
    path: "Path",
    action: "Action",
    date: "Date",
    time: "Time",
    user: "User",
    from: "From",
    to: "To",
    batch: "Batch"
  },
  documents: {
    action: "Action",
    date: "Date",
    referenceNumber: "Reference Number",
    fileName: "File Name",
    description: "Description",
    confirmdelete: "Are you sure you want to delete this document?",
    note: "Note",
    referenceDate: "Reference Date",
    documentuploadedsuccess: "Document uploaded successfully",
    documentuploadedfailed: "Document upload failed",
    documentdeletesuccess: "Document deleted successfully",
    documentdeletefailed: "Document delete failed",
    clickordragfiletothisareatoupload:
      "Click or drag file to this area to upload",
    youcanuploadonlyonefileperupload: "You can upload only one file per upload"
  },
  availability: {
    addEvent: "Add an Event",
    UpdateorDeleteEvent: "Update or Delete Event",
    StartToEnd: "Start to End Range",
    date: "Date",
    addBtn: "Add",
    updateBtn: "Update",
    delBtn: "Delete",
    weekends: "weekends",
    pickdate: "Pick Date",
    refresh: "Refresh",
    available: "available",
    duration: "Duration"
  },
  payitemsOrgPage: {
    filteroptions: "Filter Options",
    empstatus: "Employee Status",
    showactiveemponly: "Status",
    empcode: "Employee Code",
    hourly: "Hourly",
    other: "Other",
    piecework: "Piecework",
    payitemstatus: "Pay Item Status",
    stuborder: "Stub Order",
    manual: "Manual",
    payitemsOrgPage: "Pay Items",
    isExcludeFromPayroll: "Exclude From Payroll",
    payroll: "Payroll",
    otheramount: "Other Amount",
    shortcut: "Shortcut",
    payitemalreadyexists: "Pay item already exists",
    active: "Active",
    inactive: "Inactive",
    exempt: "Exempt",
    importlinkcode: "Import Link Code",
    exportlinkcode: "Export Link Code",
    time: "Time",
    doubletime: "Double Time",
    othertime: "Other Time",
    timeoff: "Time Off",
    vacation: "Vacation",
    statutoryholiday: "Statutory Holiday",
    break: "Break",
    // overtime: 'Overtime',
    regulartime: "Regular Time",
    expense: "Expense",
    absence: "Absence",
    work: "Work",
    memos: "Memos",
    accruals: "Accruals",
    reimbursements: "Reimbursements",
    employerContributions: "Employer Contributions",
    deductions: "Deductions",
    earnings: "Earnings",
    entrymethod: "Entry Method",
    entryType: "Entry Type",
    category: "Category",
    reportingcode: "Reporting code",
    assignedpayitems: "Assigned Pay Items",
    editpayitem: "Edit Pay Item",
    balance: "Balance",
    rate: "Rate",
    name: "Name",
    add: "Add",
    save: "Save",
    close: "Close",
    status: "Status",
    description: "Description",
    type: "Type",
    overtime: "Overtime Eligible",
    contribute: "Contribute to holiday time",
    chargeable: "Chargeable",
    paidfrombank: "Paid from Bank",
    paidfromamountbank: "Paid from Amount Bank",
    paidfromtimebank: "Paid from Time Bank",
    showbalance: "Block Balance Display",
    displayorder: "Display Order",
    yes: "Yes",
    no: "No",
    attendancecat: "Default Attendance Category",
    assigntogroups: "Assign to Groups",
    payitems: "Pay Items",
    payitem: "Pay Item",
    employees: "Employees",
    notes: "Notes",
    Available: "available",
    Selected: "selected",
    enterdescription: "Pay Item Description",
    selectvalue: "Select a Value",
    selectattendance: "Select Attendance Category",
    addpayitem: "Add Pay Item",
    updatepayitem: "Pay Item",
    payitemdeleted: "Payitem Deleted",
    payitemadded: "Payitem Added",
    payitemupdated: "Payitem Updated",
    payitemassignedtogroups: "Payitem Assigned to Groups",
    payitemassignedtoemployees: "Payitem Assigned to Employees",
    payitemunassignedfromemployees: "Payitem Unassigned from Employees",
    assignpayitem: "Assign Payitem",
    unassignpayitem: "Unassign Payitem",
    updateassignedpayitem: "Update Assigned Payitem",
    selectpayitemstoadd: "Select Payitems to add"
  },
  payitemsGroupPage: {
    namealreadyexists: "Name already exists",
    codealreadyexists: "Code already exists",
    systemNotes: "System notes",
    note: "Note",
    code: "Code",
    isactive: "Active",
    issystem: "System",
    isReportUse: "Use for reports",
    Actions: "Actions",
    required: "Required",
    enterPayitem: "Enter payitem group",
    enterCode: "Enter Code",
    payitemgroup: "Pay Item Group",
    payitemgroups: "Pay Item Groups",
    addpayitemgroup: "Add Payitem Group",
    updatepayitemgroup: "Pay Item Group",
    payitemgroupadded: "Payitem Group Added",
    payitemgroupupdated: "Payitem Group Updated"
  },
  attendancecategories: {
    attendancecategory: "Attendance Category",
    name: "Name",
    add: "Add",
    save: "Save",
    close: "Close",
    notes: "Notes",
    AttendanceType: "Attendance Type",
    addattendancecategory: "Add Attendance Category",
    updateattendancecategory: "Update Attendance Category",
    attendancecategorieupdated: "Attendance Category Updated"
  },
  holidayCalendar: {
    assignedholidaycalendar: "Assigned Holiday Calendar",
    holidayCalendar: "Holiday Calendar",
    name: "Name",
    namerequried: "Name is required",
    employees: "Employees",
    addholidaycalendar: "Add Holiday Calendar",
    updateholidaycalendar: "Update Holiday Calendar",
    assigntoemployees: "Assign to Employees",
    updateholiday: "Update Holiday",
    addaholiday: "Add a Holiday",
    updateordeleteholiday: "Update or Delete Holiday",
    holidayadded: "Holiday Added",
    holidayupdated: "Holiday Updated",
    holidaydeleted: "Holiday Deleted",
    allcalendars: "Holiday Calendars",
    gotocalendar: "Calendar View",
    notes: "Notes",
    clonecalendar: "Clone Calendar",
    totalholidays: "Holidays",
    importfromexistingcalendar: "Import from Existing Calendar",
    EnableConditionsforthisholiday: "Enable Conditions for this Holiday",
    dateisrequired: "Date is required"
  },
  holidayConditions: {
    holidayConditions: "Holiday Conditions",
    minimumSeniority: "Minimum Seniority",
    Employment: "Employment",
    holidayMustFallOnAScheduledWorkDay:
      "Holiday must fall on a scheduled workday",
    Employeenotabsentonthedaybeforetheholiday:
      "Employee not absent on the day before the holiday",
    Employeenotabsentonthedayaftertheholiday:
      "Employee not absent on the day after the holiday",
    Employeenotabsentonthelastscheduledworkdaybeforetheholiday:
      "Employee not absent on the last scheduled workday before the holiday",
    Employeenotabsentonthelastscheduledworkdayaftertheholiday:
      "Employee not absent on the last scheduled workday after the holiday",
    workedatleast: "Worked at least",
    daysinthelast: "days in the last",
    monthsbeforeholiday: "months before holiday",
    daysbeforeholiday: "days before holiday",
    calendardaysinthelast: "Calendar days in the last",
    Workedthatdayoftheweek: "Worked that day of the week",
    timesinthelast: "times in the last",
    EmploymentshouldbeAtleast: "Employment should be at least",
    calendardaysinthe: "calendar days in the",
    monthspriortotheholiday: "months prior to the holiday",
    seniority: "Seniority",
    employment: "Employment",
    work: "Work"
  },
  groups: {
    groups: "Groups",
    name: "Name",
    assignedgroup: "Groups",
    assigngroup: "Assign Group",
    unassigngroup: "Unassign Group",
    confirmdelete: "Are you sure you want to delete this group?",
    managers: "Managers",
    create: "Create",
    createGroup: "Create Group",
    group: "Group",
    createGroupType: "Create Group Type",
    wF: "Workflow",
    clientCode: "Code",
    comment: "Comment",
    note: "Note",
    conflicts: "Conflicts!",
    wishToReplace: "Do you wish to replace?",
    isAlreadyAssigned: "is already assigned to",
    someSelectedEmployeesAreAlreadyAssigned:
      "Some selected employees are already assigned.",
    createGroupFor: "Create New ",
    updateGroupOf: "Update Group of",
    tableHeaders: {
      groupName: "Group Name",
      groupType: "Group Type",
      numberOfEmployees: "Employees",
      numberOfManagers: "Managers",
      primaryManager: "Primary Manager",
      primary: "Primary",
      actions: "Actions"
    },
    tabs: {
      generalInfo: "General Information",
      documents: "Documents",
      properties: "Properties",
      employees: "Employees"
    }
  },
  workPlans: {
    addressLine1: "Address Line 1",
    addressLine2: "Address Line 2",
    searchLocation: "Search for a location",
    alertPeriod: "Alert Period (days)",
    alias: "Alias",
    availabilityNumber: "Number of Positions Available",
    benefitOptions: "Benefit Options",
    classes: "Classes",
    BIWEEKLY: "Biweekly",
    businessNumberFederal: "Federal Business Number",
    businessNumbers: "Business Number",
    businessNumberQuebec: "Business Number Quebec",
    businessType: "Business Type",
    cCQNumber: "CCQ Number",
    city: "City",
    clientCode: "Code",
    closePayWF: "Close Pay",
    contact: "Contact",
    contactEmail: "Contact Email",
    contactExtension: "Extension",
    contactLanguage: "Contact Language",
    contactName: "Contact Name",
    contactPhone: "Contact Phone",
    coordinates: ["Latitude", "Longitude"],
    country: "Country",
    currency: "Currency",
    linkCode: "Link Code",
    internalJobListingStatus: "Internal Job Listing Status",
    thirdPartyJobListingStatus: "3rd Party Job Listing Status",
    jobListingStatus: {
      open: "Open",
      close: "Close"
    },
    trainingIds: "Trainings",
    successionPlanWFId: "Succession Plan Workflow",
    successionPlanNote: "Succession Plan Note",
    eE: "EE Occupation group",
    eEO: "EEO Job Categories",
    eFTAccounts: "Credit Bank Accounts",
    eIn: "Empoyer Identification Number",
    employeeRecordChangeWF: "Employee record change",
    expenseWF: "Expense",
    experienceYears: "Experiance (years)",
    federalDepositSchedule: "Federal Deposit Schedule",
    federalTransmitterNumber: "Federal Transmitter Number",
    fiscalYearEndDay: "Fiscal Year End Day",
    fiscalYearEndMonth: "Fiscal Year End Month",
    FOUR_WEEKS: "Four Weeks",
    gLAccountID: "G/L Account",
    hiringLeadId: "Hiring Lead",
    incomeTaxForm: "Income Tax Form",
    isActive: "Active",
    isAllowSchedule: "Block Employee `My Team Schedule` display",
    isAllowTeamTracker: "Block Employee `My Team Tracker` display",
    isClosed: "Closed",
    isPrimary: "Primary",
    issuedBy: "Issued By",
    issuePayChequesWF: "Issue pay cheques",
    issuePayDirectDepositsWF: "Issue pay direct deposits",
    level: "Levels",
    location: "Location",
    logo: "Logo",
    maxSalary: "Maximum Salary",
    memberDescription: "Member Description",
    minSalary: "Minimum Salary",
    MONTHLY: "Monthly",
    name: "Name",
    qcOrFederal: "Quebec or Federal",
    QC: "Quebec",
    FEDERAL: "Federal",
    nameTranslate: "Name",
    nextSeqNumber: "Next Seq Number",
    nOC: "NOC Occupation Title",
    employeeAssignmentProfile: "Employee Assignment Properties",
    contactInformation: "Contact Information",
    ntfyPriorDays: "Notification preior date",
    ntfyTime: "Notification time",
    ntfyTimeZone: "Notification time zone",
    offBoardingWF: "Employee Offboarding",
    onBoardingWF: "Employee Onboarding",
    pADAccounts: "Debit Bank account",
    payCalendar: "Pay Calendar",
    payDate: "Pay Date",
    payFrequency: "Pay Frequency",
    payItems: "Pay Items",
    payRaiseWF: "Pay Raise",
    payrollYear: "Payroll Year",
    performanceReviewWF: "Performance Review",
    periodEndDate: "Period End Date",
    periodStartDate: "Period Start Date",
    phone: "Phone",
    picture: "Picture",
    planUrl: "Plan URL",
    policyNumber: "Policy Number",
    positionApprovalWF: "Position Approval",
    postalCode: "Postal Code",
    zip: "Zip",
    posting: "Position Posting",
    probationDays: "Probation Days",
    probationMonths: "Probation Months",
    proficiencies: "Proficiencies",
    proficienciesList: "Proficiencies List",
    proprietor1: "Proprietor 1 SIN",
    proprietor2: "Proprietor 2 SIN",
    providerName: "Provider Name",
    province: "Province",
    quebecTransmitterNumber: "Quebec Transmitter Number",
    remitFrequency: "Remit Frequency",
    remitFrequencyFederal: "Remit Frequency Federal",
    remitFrequencyQuebec: "Remit Frequency Quebec",
    renewalFrequency: "Renewal frequency (months)",
    transmitterNumbers: "Transmitter Numbers",
    transmitterNumber: "Transmitter Number",
    reportingToId: "Reporting to",
    reviewFrequency: "Review Frequency (months)",
    reviewTemplate: "Review Template",
    SEMI_MONTHLY: "Semi Monthly",
    sequence: "Sequence",
    skill: "Skill",
    skills: "Required Skills",
    startDate: "Start Date",
    step: "Steps",
    sUITax: "State Unemployment Insurance (SUI) tax",
    taxWithholdingCountry: "Tax Withholding Country",
    timeOffRequestWF: "Time-off",
    timeSheetPayrollSubmitWF: "Timesheet payroll submittal",
    timeSheetWF: "Timesheet",
    transitNumber: "Transit Number",
    WEEKLY: "Weekly",
    workPlanPublishDate: "Latest Schedule Publish Date",
    jobDescription: "Job Description",
    stateIdNo: {
      state: "State Name",
      idNumber: "State Id"
    },
    account: {
      bank: "Bank",
      branch: "Branch",
      accountNumber: "Account Number"
    },
    proficienciesOptions: {
      irrelevant: "Irrelevant",
      poor: "Poor",
      bellow: "Bellow",
      average: "Average",
      good: "Good",
      excellent: "Excellent",
      IRRELEVANT: "Irrelevant",
      POOR: "Poor",
      BELOW: "Bellow",
      AVERAGE: "Average",
      GOOD: "Good",
      EXCELLENT: "Excellent"
    },
    options: {
      none: "No approval required",
      levelOne: "One approval level",
      levelTwo: "Two approval level"
    },
    unionTabs: {
      unionStatuses: "Union Status",
      tradeCodes: "Trade Codes",
      sectors: "Sectors",
      categories: "Categories",
      regions: "Reigons",
      wages: "Wage Schedule"
    }
  },
  groupTypes: {
    groupTypes: "Group Types",
    groupTypeName: "Name",
    addressUsed: "Address Used",
    color: "Color",
    datedEmployeeAssignment: "Dated Employee Assignments",
    allowMultipleEmployeeAssignment:
      "Allow Multiple Employee Group Assignments",
    systemType: "System Type"
  },
  groupSystemTypes: {
    TEAM: "Team",
    DEPARTMENT: "Department",
    POLICY: "Policy",
    WORKPLAN: "Work plan",
    PAYGROUP: "Pay group",
    SITE: "Site",
    UNION: "Union",
    EMP_TYPE: "Employment Type",
    LOCATION: "Location",
    POSITION: "Position",
    EMP_STATUS: "Employment Status",
    EMPLOYER: "Employer",
    PAY_CALENDAR: "Pay Calendar",
    BENEFIT: "Benefit Plan",
    SKILL: "Skill",
    LICENSE: "Licence",
    PERMIT: "Permit",
    OTHER: "Other"
  },
  supervisors: {
    organization: "Organization",
    profile: "Profile",
    menuProfile: "Menu Profile",
    isPrimarySupervisor: "Primary Supervisor",
    isPrimaryManager: "Primary Manager",
    createAndModifyPunches: "Create & Modify Punches",
    temporaryOnboarding: "Temporary Onboarding",
    timeSheetApproval: "Timesheet Approval",
    timeOffRequestApproval: "Time-off Request Approval",
    expenseReimbursementApproval: "Expense Reimbursement Approval",
    employeeProfiles: "Employee Profiles",
    employeePayStubs: "Employee Paystubs",
    employeeTimeSheet: "Employee Timesheets",
    employeeConfidentialInformation: "Employee Confidential Information",
    employeeSchedules: "Employee Schedules",
    employeeExpenseReimbursement: "Employee Expense Reimbursements",
    employeePayRates: "Employee Pay Rates",
    performanceReviews: "Performance Reviews",
    EmployeeTimeOffRequests: "Employee Time-off Requests",
    timeSheetSubmittal: "Timesheet Submittal",
    timeOffRequestSubmittal: "Time-off Request Submittal",
    expenseReimbursementSubmittal: "Expense Reimbursement Submittal",
    issuePayChequeApprovalLevel: "Issue Pay Cheques Approval",
    issuePayDirectDepositApprovalLevel: "Issue Pay Direct Deposits Approval",
    accessTemplate: "Employee Templates",
    closePayApprovalLevel: "Close Pay Approval",
    payItems: "Pay Items",
    actions: "Actions",
    onBoard: "Onboard",
    offBoard: "Offboard",
    invite: "Invite",
    both: "Both",
    onboardApproval: "Onboard Approval",
    offboardApproval: "Offboard Approval",
    performanceApproval: "Performance Reviews Approval",
    positionApproval: "Position Changes Approval",
    accessPosition: "Position Change",
    onboardNtfy: "Onboard Submittal",
    offboardNtfy: "Offboard Submittal",
    performanceNtfy: "Performance Reviews Submittal",
    positionNtfy: "Position Change Submittal",
    closePayNtfyLevel: "Close Pay Notification",
    issuePayDirectDepositNtfyLevel: "Issue Pay Direct Deposit",
    issuePayChequeNtfyLevel: "Issue Pay Cheques",
    onboardOffboard: "Onboarding / Offboarding",
    accessCalendar: "Pay and Holiday Calenders",
    menuTemplate: "Menu Template",
    selectMenuTemplate: "Select a menu template",
    tabs: {
      permissions: "Permissions",
      authorityLevel: "Authority Level",
      accessLevel: "Access Level",
      notificationLevel: "Notification Level"
    },
    placeholders: {
      select: "Select"
    },
    options: {
      none: "None",
      all: "All",
      hide: "Hide",
      view: "View",
      modify: "Modify",
      create: "Create",
      delete: "Delete",
      levelOne: "Level One",
      levelTwo: "Level Two"
    }
  },
  modals: {
    createGroupType: "Create Group Type",
    updateGroupType: "Update Group Type",
    createGroup: "Create Group",
    updateGroup: "Update Group",
    createSupervisor: "Create Manager"
  },
  form: {
    general: {
      fieldisrequired: "This field is required",
      submit: "Submit",
      save: "Save",
      name: "Name",
      note: "Note",
      clientcode: "Client Code",
      reportingcode: "Reporting Code",
      displaysequence: "Sequence",
      mandatory: "Mandatory",
      active: "Active",
      inactive: "Inactive",
      geoposition: "Geo Position"
    },
    group: {
      general: {
        name: "Name",
        groupType: "Type",
        parentGroup: "Parent Group"
      },
      team: {
        expenseWF: "Expense workflow",
        timeSheetPayrollSubmitWF: "Timesheet payroll submittal workflow",
        timeSheetWF: "Timesheet workflow",
        timeOffRequestWF: "Time-off workflow"
      },
      department: {
        offBoardingWF: "Employee Offboarding workflow",
        onBoardingWF: "Employee Onboarding workflow",
        payRaiseWF: "Pay Raise workflow",
        positionApprovalWF: "Position Approval workflow",
        recordChangeWF: "Employee record change workflow"
      },
      paygroup: {
        closePayWF: "Close Pay workflow ",
        issuePayChequesWF: "Issue Pay Direct Deposits workflow",
        issuePayDirectDepositsWF: "Issue Pay Cheques workflow "
      },
      address: {
        addressLine1: "Address 1",
        addressLine2: "Address 2",
        city: "City",
        country: "Country",
        location:
          "GPS coordinates / Choose Address ID Internet to enter or view Internet information",
        phone: "Phone ",
        picture: "Picture",
        postalCode: "Zip code / Postal code",
        province: "State / Province"
      }
    }
  },
  notification: {
    success: {
      add: "Item Sucessfully Added",
      update: "Item Sucessfully Updated",
      delete: "Item Sucessfully Removed"
    }
  },
  trackingsegments: {
    assigntrackingsegment: "Assign Tracking Segment",
    assignedTrackingSegments: "Assigned Tracking Segments",
    displaysequence: "Display Sequence",
    trackingitemsfor: "Tracking Items for",
    itemswillberemoved: "Items will be removed",
    bulkdeletetrackingitems: "Bulk Delete Tracking Items",
    viewtrackingitems: "View Tracking Items",
    addtrackingsegment: "Add Tracking Segment",
    updatetrackingsegment: "Tracking Segment",
    addtrackingitem: "Add Tracking Item",
    updatetrackingitem: "Update Tracking Item",
    trackingsegments: "Tracking Segments",
    type: "Type",
    validationlistdisplay: "Display Choice",
    validationlistdisplaytype: "Display Choice",
    validationmethod: "Validation",
    freeform: "Freeform",
    grouptype: "Group Type",
    logical: "Logical",
    integer: "Integer",
    numeric: "Numeric",
    list: "List",
    jira: "Jira",
    position: "Position",
    project: "Project",
    code: "Code",
    name: "Name",
    both: "Name and Code"
  },
  assets: {
    assets: "Assets",
    assignments: "Assignments",
    assignmentsOf: "Assignments of",
    createAsset: "Create Asset",
    editAsset: "Edit Asset",
    isActive: "Status",
    assetName: "Name",
    note: "Note",
    code: "Code",
    linkCode: "Link Code",
    serialNo: "Serial Number",
    config: "Configuration",
    vendor: "Vendor",
    purchaseDate: "Purchase Date",
    cost: "Cost",
    currency: "Currency",
    dueDatePeriod: "Due Date Alert Period",
    nextScheduleDate: `Next Scheduled Maintenance Date`,
    action: "Action",
    contact: "Contact",
    contactName: "Contact Name",
    contactPhone: "Contact Phone",
    contactEmail: "Contact Email",
    properties: "Properties",
    documents: "Documents",
    employeeAssignment: "Employee Assignment",
    assignAssetToEmployee: "Assign Asset To Employee",
    employee: "Employee",
    issueDate: "Issue Date",
    dueDate: "Due Date",
    returnDate: "Return Date",
    status: "Status",
    onlyShowAvailableAssets: "Only Show Available Assets",
    createAssset: "Create Asset",
    updateAsset: "Edit Asset",
    createAssignment: "Create Assignment",
    updateAssignment: "Edit Assignment",
    setReturnDateToToday: "Set Return Date to Today",
    image: "Image"
  },
  performance: {
    list: "List",
    month: "Month",
    week: "Week",
    at: "at",
    addPerformanceReview: "Add Performance Review",
    editPerformanceReview: "Edit Performance Review",
    reviewStatus: "Status",
    reviewDate: "Review Date/Time",
    period: "Review Period (months)",
    duration: "Duration (minutes)",
    evaluatorProfile: "Evaluator",
    employeeProfile: "Employee",
    location: "Review Location",
    alertInDays: "Review Alert (days)",
    alertInMinutes: "Review Alert (minutes)",
    positionGroup: "Position",
    reviewScore: "Review Score",
    general: "General",
    scores: "Scores",
    performanceReviewCategory: "Category",
    score: "Score",
    note: "Note",
    action: "Action",
    evaluatorNote: "Evaluator",
    employeeNote: "Employee",
    signature: "Signature",
    reviewFor: "Review For",
    reviewBy: "Review By",
    latestEvaluation: "Latest Evaluation (date)",
    attachments: "Attachments",
    reviewWf: "Review Workflow",
    wfStatus: "Workflow Status: ",
    reviewStatuses: {
      TBD: "TBD",
      WF: "Workflow",
      PROPOSED: "Proposed",
      DRAFT: "Draft",
      INVITE: "Invited",
      ACKNOWLEDGED: "Acknowledged",
      PENDING: "Pending",
      COMPLETED: "Completed",
      ON_HOLD: "On Hold",
      FOLLOW_UP: "Follow Up"
    }
  },
  training: {
    profile: "Profile",
    sign: "Signature",
    addAssignment: "Add Assignment",
    actions: "Actions",
    issueDate: "Issue Date",
    evaluation: "Evaluation",
    dueDate: "Due Date",
    fullName: "Full Name",
    trainingStatus: "Training Status",
    completionDate: "Completion Date",
    assign: "Assign",
    assignmentsOf: "Assignments of ",
    addTraining: "Add Training",
    code: "Code",
    name: "Name",
    linkCode: "Link Code",
    status: "Status",
    active: "Active",
    note: "Note",
    // urlList: 'URL List & Credentials',
    urlList: "URL List",
    url: "URL",
    assignedTo: "Employees",
    general: "General",
    documents: "Documents",
    recurrence: "Recurrence (months)",
    reqSign: "Required Signatures",
    createTraining: "Create Training",
    updateTraining: "Update Training"
  },
  languages: {
    EN: "English",
    FR: "French",
    "hr-IL": "Hebrew"
  },
  monthsInNum: {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
  },
  signer: {
    clickToSign: "Click to sign",
    removeSign: "Remove Signiture",
    signedOn: "Signed on",
    signedBy: "Signed by"
  },
  breadcrumbs: {
    home: "Home",
    unknownPage: "Unknown Page",
    groups: "Groups",
    unknownType: "Unknown Type",
    workforce: "Workforce",
    employeeGroups: "Employee Groups",
    attendance: "Attendance",
    team: "Team",
    organization: "Organization",
    locations: "Locations",
    unions: "Unions",
    advanced: "Advanced",
    employeeTypes: "Employee Types",
    departments: "Departments",
    positions: "Positions",
    benefitPlans: "Benefit Plans",
    licenses: "License & Permits",
    skills: "Skills",
    pay: "Pay",
    employers: "Employers",
    payGroups: "Pay Groups",
    availability: "Availability",
    trackingSegments: "Tracking Segments",
    assets: "Assets",
    calendars: "Calendars",
    holidays: "Holidays",
    employees: "Employees",
    organizationChart: "Organization Chart",
    performance: "Performance",
    training: "Training",
    items: "Items",
    payItems: "Pay Items",
    payItemGroups: "Pay Item Groups",
    workflow: "Work Flow",
    workflowSteps: "Workflow Steps",
    steps: "Steps",
    workflowAssignments: "Workflow Assignments",
    assignments: "Assignments"
  },
  wF: {
    wF: "Workflow",
    wFTransition: "Workflow Transitions",
    transitionFrom: "Transition from",
    noStateError: "Please add at least one state",
    status: "Status",
    active: "Active",
    name: "Name",
    type: "Type",
    actions: "Actions",
    transitions: "Transitions",
    steps: "Steps",
    actionList: "Action List",
    note: "Note",
    contacts: "Contacts",
    general: "General",
    updateWF: "Update Workflow",
    addWF: "Add Workflow",
    contactProfileOne: "Contact 1",
    contactProfileTwo: "Contact 2",
    fromStatus: "Form Status",
    toStatus: "To Status",
    tasks: "Tasks",
    task: "Task",
    nt: "Notification Template",
    checklist: "Checklist",
    assign: "Assign",
    addTransition: "Add Transition",
    updateTransition: "Update Transition",
    fullName: "Full Name",
    profile: "Profile",
    effectiveDate: "Effective Date",
    state: "State",
    fromState: "From State",
    toState: "To State",
    addChecklist: "Add Checklist",
    assigned: "Assigned!",
    unassigned: "Unassigned!",
    moveToNextStep: "Move to Next Step",
    types: {
      ONBOARDING: "Onboarding",
      OFFBOARDING: "Offboarding",
      REVIEW: "Performance Review"
    },
    noChecklist: "No Checklist!",
    noTransition: "No Transition!",
    moveFrom: "Move From",
    to: "To",
    setTo: "Set To",
    logs: "Logs",
    logsFor: "Logs for ",
    user: "User: ",
    undoLastTransition: "Undo Last Transition",
    wantToRunAction:
      "Do you want to run this action from current state to previous?",
    yesRunActions: "Yes, run actions",
    noDeleteLastTransition: "No, delete last transition",
    actionsFiredSuccessfully: " Actions Fired Successfully!",
    checklistStatuses: {
      PENDING: "Pending",
      COMPLETED: "Completed",
      NA: "Not Applicable"
    },
    defaultStates: {
      START: "Start",
      IN_PROGRESS: "In Progress",
      CANCELLED: "Cancelled",
      REJECTED: "Rejected",
      ON_HOLD: "On Hold",
      FOLLOW_UP: "Follow Up",
      COMPLETED: "Completed"
    },
    actionsList: {
      ACTIVATE_PROFILE: "Activate Profile",
      DEACTIVATE_PROFILE: "Deactivate Profile",
      EMP_STATUS_PART_TIME: "Employee Status - Part Time",
      EMP_STATUS_FULL_TIME: "Employee Status - Full Time",
      EMP_STATUS_CASUAL: "Employee Status - Casual",
      EMP_STATUS_CONTRACT: "Employee Status - Contract",
      EMP_STATUS_STUDENT: "Employee Status - Student",
      EMP_STATUS_ONBOARD: "Employee Status - Onboarding",
      EMP_STATUS_TERMINATED: "Employee Status - Terminated",
      NOTIFY_EMP: "Notify Employee",
      NOTIFY_SUPERVISOR: "Notify Supervisor",
      NOTIFY_HR_MANAGER: "Notify HR Manager",
      NOTIFY_PAY_MANAGER: "Notify Pay Manager",
      NOTIFY_CONTACT1: "Notify Contact 1",
      NOTIFY_CONTACT2: "Notify Contact 2",
      RESET: "Reset"
    },
    createWfWithTypeOnboarding:
      "Please create at least one workflow woth type of Onboarding"
  },
  templates: {
    general: "General",
    name: "Name",
    templateType: "Template Type",
    INVITATION: "Invitation",
    HIRE: "Hire",
    EMPLOYEE_WELCOME: "Employee Welcome",
    EMAIL_TO_EMPLOYEE: "Email to Employee",
    active: "Active",
    note: "Note",
    email: "Email",
    htmlMessage: "HTML Message",
    placeholders: "Placeholders",
    clickAndPaste: "Click and Paste above",
    sms: "SMS",
    smsMessage: "SMS Message",
    pushNotification: "Push Notification",
    status: "Status",
    isSystem: "System",
    action: "Action",
    addTemplate: "Add Notification Template",
    employeeFirstName: "Employee First Name",
    employeeLastName: "Employee Last Name",
    supervisorFirstName: "Supervisor First Name",
    supervisorLastName: "Supervisor Last Name",
    managerFirstName: "Manager First Name",
    managerLastName: "Manager Last Name",
    date: "Date",
    dateAsText: "Date as Text",
    timeAmPm: "Time (AM/PM)",
    time24h: "Time (24h)",
    companyName: "Company Name",
    companyLogo: "Company Logo",
    copied: "Copied!"
  },
  applicant: {
    status: "Status",
    jobTitle: "Job Title",
    position: "Position",
    firstName: "First Name",
    lastName: "Last Name",
    personalPhone: "Personal Phone, Cell",
    personalEmail: "Personal Email",
    cvAttachment: "CV Attachment",
    coverLetter: "Cover Letter",
    email: "Email",
    fullName: "Full Name",
    active: "Active",
    progress: "Progress",
    actions: "Actions",
    general: "General",
    emailTemplate: "Email Template",
    saveAndGoTo: "Save and go to ",
    pleaseSelectTemplate: "Please Select a template",
    addApplicant: "Add Applicant",
    wfId: "Workflow",
    APPLICANT: "Applicant",
    CANDIDATE: "Candidate",
    wfStatus: "Workflow Status",
    employer: "Employer",
    applicationStatus: "Application Status",
    firstSave: "Please first save the documnet and then try"
  },
  uploader: {
    title: "Click or drag file to this area to upload",
    subtitle:
      "Support for a single or bulk upload. Strictly prohibit from uploading company data or other band files",
    sync: "Sync Documnets",
    singleTitle: "Click to upload"
  }
};

export default messages;
