const messages = {
  'topBar.actions': 'Actions',
  'topBar.status': 'Status',
  'topBar.profileMenu.hello': 'Hello',
  'topBar.profileMenu.billingPlan': 'Billing Plan',
  'topBar.profileMenu.role': 'Role',
  'topBar.profileMenu.email': 'Email',
  'topBar.profileMenu.phone': 'Phone',
  'topBar.profileMenu.editProfile': 'Edit Profile',
  'topBar.profileMenu.changePassword': 'Change Password',
  'topBar.profileMenu.changeEmail': 'Change Email',
  'topBar.profileMenu.theme': 'Theme',
  'topBar.profileMenu.light': 'Light',
  'topBar.profileMenu.dark': 'Dark',
  'topBar.profileMenu.logout': 'Logout',
  gender: {
    MALE: 'Male',
    FEMALE: 'Female',
    OTHER: 'Other',
    UNKNOWN: 'Other',
  },
  rules: {
    atleastOneBank: 'Minimum one bank account required',
    notValidPhone: 'Enter valid phone number format',
  },
  enums: {
    FREEFORM: 'Freeform',
    GROUPTYPE: 'Group Type',
    INTEGER: 'Integer',
    LIST: 'List',
    LOGICAL: 'Logical',
    NUMERIC: 'Numeric',
    CODE: 'Code',
    NAME: 'Name',
    NAME_CODE: 'Name and Code',
  },
  permissions: {
    NNN: 'Hidden',
    RNN: 'Read-Only',
    RWN: 'Read-Write',
    RWD: 'Read-Write-Delete',
  },
  pushNotification: {
    EMAIL: 'Email',
    SMS: 'SMS',
    PUSH: 'Push Notification',
  },
  paymentMethod: {
    DIRECT_DEPOSIT: 'Direct Deposit',
    PAY_CHEQUE: 'Pay Cheque',
    OTHER: 'Other',
  },
  onlineStatus: {
    AVAILABLE: 'Available',
    OUT_OF_OFFICE: 'Out of office',
    IN_A_MEETING: 'In a meeting',
    AWAY: 'Away',
    BUSY: 'Busy',
    DO_NOT_DISTURB: 'Do not disturb',
    BE_RIGHT_BACK: 'Be right back',
    OFFLINE: 'Offline',
    WORKING_REMOTLY: 'Working remotely',
  },
  modalTitles: {
    assignPosition: 'Assign Position',
    assignStatus: 'Assign a new status',
  },
  relationStatus: {
    MARRIED: 'Married',
    SINGLE: 'Single',
    SINGLE_PARENT: 'Single Parent',
    UNKNOWN: 'Unknown',
    OTHER: 'Other',
    FAMILY: 'Family',
  },
  paymentType: {
    HOURLY: 'Hourly',
    SALARY: 'Salary',
    OTHER: 'Other',
  },
  statusEnum: {
    PENDING1: 'Pending 1',
    PENDING2: 'Pending 2',
    APPROVED: 'Approved',
    REJECTED: 'Rejected',
    CANCELLED: 'Cancelled',
  },
  degree: {
    BACHELOR: 'Bachelor',
    COLLEGE: 'College',
    MASTER: 'Master',
    PHD: 'PhD',
    PRIMARY: 'Primary',
    SECONDARY: 'Secondary',
    TRADE_SCHOOL: 'Trade School',
  },
  general: {
    assigned: 'Assigned',
    back: 'Back',
    description: 'Description',
    inactive: 'INACTIVE',
    invalidEntry: 'Invalid entry',
    profiles: 'Profiles',
    name: 'Name',
    clone: 'Clone',
    note: 'Note',
    start: 'Start',
    end: 'End',
    searchAddress: 'Find Address',
    restricted: 'Restricted',
    isActive: 'Active',
    setDefault: 'Set Default',
    years: 'years',
    duedate: 'Due Date',
    issueDate: 'Issue Date',
    yearsOld: 'years old',
    empID: 'Employee ID',
    idNumber: 'ID Number',
    attachments: 'Attachments',
    properties: 'Properties',
    type: 'Type',
    employmentType: 'Employment Type',
    employer: 'Employer',
    active: 'Active',
    empStatus: 'Employee Status',
    employmentStatus: 'Employment Status',
    groupName: 'Group Name',
    effectiveDate: 'Effective Date',
    expiryDate: 'Expiry Date',
    approvedOn: 'Approved On',
    approvedBy: 'Approved By',
    asof: 'as of',
    general: 'General',
    position: 'Position',
    additionalproperties: 'Additional Properties',
    ok: 'Ok',
    reset: 'Reset',
    order: 'Order',
    actions: 'Actions',
    allemp: 'All Employees',
    delete: 'Delete',
    cancel: 'Cancel',
    bulkactions: 'Bulk Actions',
    bulkdelete: 'Bulk Delete',
    invalidvalueerror: 'Invalid value',
    invalidPhoneFormat: 'Invalid Phone Format',
    invalidSinNumber: 'Invalid Sin Number',
    duplicatenameerror: 'Duplicate name error',
    home: 'Home',
    dataadded: 'Data added',
    datadeleted: 'Data deleted',
    dataupdated: 'Data updated',
    Compensation: 'Compensation',
    reloadpage: 'Reload',
    noData: 'No data',
    success: 'Success',
    areYouSure: 'Are you sure?',
    confirmdelete: 'Are you sure you want to delete this item?',
    failed: 'Failed',
    servererror: 'Server error. Please try again',
    somethingwentwrong: 'Something went wrong',
    deleted: 'Deleted',
    informationadded: 'Information added',
    informationupdated: 'Information updated',
    informationdeleted: 'Information deleted',
    days: 'Days',
    weeks: 'Weeks',
    months: 'Months',
    period: 'Period',
    details: 'Details',
    conditions: 'Conditions',
    status: 'Status',
    nofieldsaremodified: 'No fields are modified',
    info: 'Info',
    thisactionwilleffectassignedemployeesaswell:
      'This action will effect assigned employees as well',
    payitemassignmentstatuswillbeupdatedforallassignedemployees:
      'Pay item assignment status will be updated for all assigned employees',
    trackingitemsforthissegmentwillberemoved: 'Tracking items for this segment will be removed',
    yes: 'Yes',
    no: 'No',
    selectGroupType: 'Select Group Type',
    filterByGroup: 'Filter By Group',
    payCalendar: 'Pay Calendar',
  },
  orgSettings: {
    orgSettings: 'Organization Settings',
    general: 'General',
    billing: 'Billing',
    properties: 'Organization Properties',
    defaults: 'Defaults',
    systemConfig: 'System configuration',
    customProperties: 'Custom Properties',
    access: 'Access',
    shortName: 'Short Name',
    website: 'Website',
    defaultCurrency: 'Default Currency',
    defaultTimeZone: 'Default Time Zone',
    bands: 'Bands',
    noc: 'National Occupation Classification',
    clientCode: 'Client Code',
    reviewScoreType: 'Review Score Type',
  },
  editProfile: {
    tabs: {
      basicInfo: 'Basic Info',
      personal: 'Personal',
      compensation: 'Compensation',
      taxation: 'Taxation',
      groups: 'Groups',
      preferences: 'Preferences',
      benefitplan: 'Benefit Plan',
      union: 'Union',
      skills: 'Skills',
      licenseAndPermit: 'Licenses & Permits',
      training: 'Training',
      assets: 'Assets',
      notes: 'Notes',
      contactsAndFamily: 'Contacts & Family',
      payitems: 'Pay Items',
      trackingsegments: 'Tracking Segments',
      hr: 'Human Resources',
      education: 'Education',
      criminalRecord: 'Criminal Record',
      notifications: 'Notifications',
      permissions: 'Permissions',
      user: 'User',
      general: 'General',
      address: 'Address',
      bankAccounts: 'Bank Accounts',
      payment: 'Payment',
      nonResident: 'Non Resident',
      digitalIDs: 'Digital IDs',
      otherIds: 'Other IDs',
      organizationProperties: 'Organization Properties',
      previousEmployer: 'Previous Employer',
      documents: 'Documents',
    },
    selectEmployee: 'Select an Employee',
    sources: {
      EMP_TEMPLATE: 'Template',
      PAYEE: 'Payee',
      CANDIDATE: 'Candidate',
    },
    personalTab1: 'Personal Email, Phone, Date of Birth and more',
    personalTab2: 'Address, Postal Code, Country',
    personalTab3: 'Bank Name, Account Number, Routing Number',
    personalTab4: 'School, Degree, Major, GPA, Graduation Year',
    personalTab5: 'ID Type, Number, Expiry Date',
    personalTab6: 'Other Settings',
    nonResident: 'Non-Resident',
    organizationProperties: 'Organization Properties',
    organization: {
      canada: {
        band: 'Band',
        noc: 'National Occupation Classification',
        employeeEquityDesignatedGroups: 'Employee Equity Designated Groups',
        employeeEquityOccupationalGroups: 'Employee Equity Occupational Groups',
      },
      us: {
        isFLSAExempt: 'FLSA Exempt',
        eEOJob: 'EEO Job',
        eEOEthnicity: 'EEO Ethinicity',
        workersCompClass: 'Workers Comp Class',
        EmployeeTaxFilingStatus: 'Employee Tax Filing Status',
      },
    },
    digitalIds: 'Digital IDs',
    digitalIdsExtra: 'Digital IDs with name and pictures',
    bankAccounts: 'Bank Accounts',
    payment: 'Payment',
    idNumbers: 'Other IDs',
    other: 'Other',
    level: 'Level',
    step: 'Step',
    primary: 'Primary',
    editProfile: 'Edit Profile',
    benefitplan: 'Benefit Plan',
    medicalAlert: 'Medical Alert',
    avatar: 'Avatar',
    picture: 'Picture',
    addBenefitPlan: 'Add Benefit Plan',
    documents: {
      title: 'Documents',
      addDocuments: 'Add Documents',
      documentType: 'Document Type',
      uploadedDate: 'Uploaded Date',
    },
    assets: {
      assets: 'Assets',
      returndate: 'Return Date',
      assignasset: 'Assign Asset',
      assignedassets: 'Assigned Assets',
      overdue: 'Overdue',
    },
    training: {
      training: 'Training',
      trainingRecords: 'Training Records',
      addNewTrainingRecord: 'Add New Training Record',
      status: 'Status',
      completionDate: 'Completion Date',
      evaluation: 'Evaluation',
      signId: 'Sign ID',
      signed: 'Signed',
      note: 'Note',
      statuses: {
        IN_PROGRESS: 'In Progress',
        COMPLETED: 'Completed',
        PENDING: 'Pending',
        CANCELLED: 'Cancelled',
      },
    },
    union: {
      union: 'Union',
      addUnion: 'Add Union',
    },
    skills: {
      skills: 'Skills',
      proficiency: 'Proficiency',
      experienceinyears: 'Experience in years',
      experienceasofdate: 'Experience as of date',
    },
    licenseAndPermit: {
      licenseAndPermit: 'License and Permit',
      id: 'ID',
      addLicense: 'Add License',
      assignedlicenseandpermit: 'Assigned Licenses & Permits',
    },
    benefitOption: {
      override: 'Override',
      optout: 'Opt-out',
      assignedBenefitPlans: 'Assigned Benefit Plans',
      benefitOption: 'Option',
      idNumber: 'ID',
      class: 'Class',
      benefitStatus: 'Benefit Status',
      claim: 'Claim Dependents',
      overrideannualearnings: 'Annual Earnings',
      overridedefaultcoverage: 'Default Coverage',
      optoutmedical: 'Opt-out Medical',
      optoutdental: 'Opt-out Dental',
      optoutadnd: 'Opt-out AD&D',
      optoutclinicalillness: 'Opt-out Critical Illness',
      smoker: 'Smoker',
      evidence: 'Evidence',
      memberDescription: 'Member Description',
    },
    benefitTableData: {
      memberDescription: 'Member Description',
      name: 'Name',
      option: 'Option',
      ID: 'ID',
      class: 'Class',
      status: 'Status',
      expiry: 'Expiry',
    },
    unionTableData: {
      expiry: 'Expiry',
      name: 'Name',
      category: 'Category',
      ID: 'ID',
      region: 'Region',
      sector: 'Sector',
      tradeCode: 'Trade Code',
      unionStatus: 'Union Status',
      trade: 'Trade',
      wage: 'Wage',
      addUnion: 'Add Union',
      assignedUnion: 'Assigned Union',
    },
    skillsTableData: {
      proficiency: 'Proficiency',
      experience: 'Experience',
      addSkill: 'Add Skill',
      assignedSkills: 'Assigned Skills',
    },
    taxation: {
      federal: 'Federal',
      Provincial: 'Provincial',
      taxation: 'Taxation',
      province: 'Province',
      taxFormula: 'Tax Formula',
      taxFormulas: {
        PERIODIC: 'Periodic',
        NON_PERIODIC: 'Non-Periodic',
        EXEMPT: 'Exempt',
        STATUS_INDIAN: 'Status Indian',
      },
      bandNumber: 'Band Number',
      tfc: 'Total Federal Claim',
      eft: 'Extra Federal Tax',
      afd: 'Annual Federal deduction',
      bonusMethod: 'Tax method for bonus',
      bonusMethods: {
        FIXED_RATE: 'Fixed Rate',
        ESTIMATED_RATE: 'Estimated Annual Income',
      },
      taxRateForBonus: 'Federal Tax rate for bonus',
      eafi: 'Estimated annual federal income',
      ftf: 'Federal Tax Form',
      dfpz: 'Deduction for prescribed zone',
      t4ecfb29: 'T4 Employment code for box 29',
      nod: 'Number of dependents',
      ebn: 'Employee Business Number',
      cm: 'Commission Employee',
      tqc: 'Total Quebec Claim',
      eqt: 'Extra Quebec Tax',
      aqd: 'Annual Quebec deduction',
      qtrfb: 'Quebec tax rate for bonus',
      eaqi: 'Estimated annual Quebec income',
      canada: 'Canada',
      qc: 'Quebec',
      rRRDPSP: 'RPP/ DPSP Account',
    },
    bankAccountsTab: {
      addAccount: 'Add Account',
      bank: 'Bank',
      branch: 'Branch',
      accountNumber: 'Account Number',
      splitMethod: 'Split Method',
      splitMethods: {
        BALANCE: 'Balance',
        PERCENTAGE: 'Percentage',
        FIXED_AMOUNT: 'Fixed Amount',
      },
      amount: 'Amount',
      percentage: 'Percentage',
      description: 'Description',
      errorCodes: {
        moreThan100: 'Total percentage is more than 100',
        lessThan100: 'Less than 100 percent',
        needBalance: 'Please add balance account',
        wrongAccount: 'Please Enter Valid Account Number',
        wrongBank: 'Please Enter Valid Bank Number',
        wrongBranch: 'Please Enter Valid Branch Number',
      },
      chequeSample: 'Cheque Specimen',
      uploadVoidCheque: 'Upload Void Cheque',
    },
    idNumberTab: {
      add: 'Add ID',
    },
  },
  countries: {
    CA: 'Canada',
    US: 'United States of America',
  },
  warnings: {
    reportUse: 'Use for reposts',
    datamodified: 'Data Modified',
    exitwithoutsave: 'Do you wish to skip your changes?',
  },
  provinces: {
    CA: {
      AB: 'Alberta',
      BC: 'British Columbia',
      MB: 'Manitoba',
      NB: 'New Brunswick',
      NL: 'Newfoundland & Labrador',
      NS: 'Nova Scotia',
      NT: 'Northwest Territories',
      NU: 'Nunavut',
      ON: 'Ontario',
      PE: 'Prince Edward Island',
      QC: 'Quebec',
      SK: 'Saskatchewan',
      YT: 'Yukon',
    },
    US: {
      AL: 'Alabama',
      AK: 'Alaska',
      AZ: 'Arizona',
      AR: 'Arkansas',
      CA: 'California',
      CO: 'Colorado',
      CT: 'Connecticut',
      DE: 'Delaware',
      DC: 'District Of Columbia',
      FL: 'Florida',
      GA: 'Georgia',
      HI: 'Hawaii',
      ID: 'Idaho',
      IL: 'Illinois',
      IN: 'Indiana',
      IA: 'Iowa',
      KS: 'Kansas',
      KY: 'Kentucky',
      LA: 'Louisiana',
      ME: 'Maine',
      MD: 'Maryland',
      MA: 'Massachusetts',
      MI: 'Michigan',
      MN: 'Minnesota',
      MS: 'Mississippi',
      MO: 'Missouri',
      MT: 'Montana',
      NE: 'Nebraska',
      NV: 'Nevada',
      NH: 'New Hampshire',
      NJ: 'New Jersey',
      NM: 'New Mexico',
      NY: 'New York',
      NC: 'North Carolina',
      ND: 'North Dakota',
      OH: 'Ohio',
      OK: 'Oklahoma',
      OR: 'Oregon',
      PA: 'Pennsylvania',
      RI: 'Rhode Island',
      SC: 'South Carolina',
      SD: 'South Dakota',
      TN: 'Tennessee',
      TX: 'Texas',
      UT: 'Utah',
      VT: 'Vermont',
      VA: 'Virginia',
      WA: 'Washington',
      WV: 'West Virginia',
      WI: 'Wisconsin',
      WY: 'Wyoming',
    },
  },
  relationships: {
    AUNT: 'Aunt',
    BOYFRIEND: 'Boyfriend',
    BROTHER: 'Brother',
    'BROTHER-IN-LAW': 'Brother-in-law',
    CONTACT: 'Contact',
    DAUGHTER: 'Daughter',
    'EX-HUSBAND': 'Ex-Husband',
    'EX-WIFE': 'Ex-Wife',
    FATHER: 'Father',
    'FATHER-IN-LAW': 'Father-in-law',
    FIANCE: 'Fiance',
    FIANCEE: 'Fiancee',
    FRIEND: 'Friend',
    GIRLFRIEND: 'Girlfriend',
    GRANDFATHER: 'Grandfather',
    GRANDMOTHER: 'Grandmother',
    HUSBAND: 'Husband',
    MOTHER: 'Mother',
    'MOTHER-IN-LAW': 'Mother-in-law',
    NEIGHBOUR: 'Neighbor',
    NEPHEW: 'Nephew',
    NIECE: 'Niece',
    PARTNER: 'Partner',
    RELATIVE: 'Relative',
    SISTER: 'Sister',
    'SISTER-IN-LAW': 'Sister-in-law',
    SON: 'Son',
    SPOUSE: 'Spouse',
    'STEP-DAUGHTER': 'Step-daughter',
    'STEP-FATHER': 'Step-father',
    'STEP-MOTHER': 'Step-mother',
    'STEP-SON': 'Step-son',
    UNCLE: 'Uncle',
    UNKNOWN: 'Unknown',
    WIFE: 'Wife',
  },
  roles: {
    ORG_ADMIN: 'Org Admin',
    EMPLOYEE: 'Employee',
    SUPERVISOR: 'Supervisor',
    SUPERVISORS: 'Supervisors',
    PAY_MANAGER: 'Pay Managers',
    HR_MANAGER: 'HR Managers',
    SYS_ADMIN: 'System Admin',
    MANAGERS: 'Managers',
    MANAGER: 'Manager',
  },
  groupRole: {
    SUPERVISORS: 'Assign Supervisor(s)',
    PAY_MANAGER: 'Assign Pay Manager(s)',
    HR_MANAGER: 'Assign HR Manager(s)',
  },
  dashboard: {
    dashboard: 'Dashboard',
    editProfile: 'Edit Profile',
    employees: 'Employees',
    totalDocuments: 'Total documents',
    teams: 'Teams',
    attendancePolicies: 'Attendance Policies',
    workPlan: 'Work Plan',
    latestTimeOff: 'Latest submitted time-off requests ',
    latestDoc: 'Latest Document Dates',
    supervisor: 'Supervisor',
    leftPanel: {
      availability: 'Availability',
      presently: 'Presently',
      code: 'Code',
      badge: 'Badge',
      cell: 'Cell',
      work: 'Work',
      email: 'Email',
      groups: 'Groups',
      expiredGroups: 'Expired Groups',
      lastlogin: 'Last Login',
      expiredAssets: 'Overdue Assets',
    },
  },
  buttons: {
    add: 'Add',
    update: 'Update',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    dontSave: 'Dont Save',
    search: 'Search',
    clear: 'Clear',
    close: 'Close',
    edit: 'Edit',
    view: 'View',
    addNew: 'Add New',
    addNewEmployee: 'Add a new Employee',
    columns: 'Columns',
    assigntoemployees: 'Assign Employees',
    modify: 'Modify',
    export: 'Export',
    upload: 'Upload',
  },
  exitModal: {
    title: 'You have unsaved changes.',
    description: 'Do you wish to save your changes?',
  },
  profile: {
    terminationId: 'Termination ID',
    basicInfo: {
      isActive: 'Active',
      title: 'Basic Info',
      firstName: 'First Name',
      lastName: 'Last Name',
      fullName: 'Full Name',
      availabilityStatus: 'Availability',
      workEmail: 'Work Email',
      personalEmail: 'Personal Email',
      workPhone: 'Work Phone',
      workPhoneS: 'Work',
      cellPhone: 'Personal Cell Phone',
      cellPhoneS: 'Personal',
      personalPhone: 'Personal Phone',
      workcellphone: 'Work Cell Phone',
      homePhone: 'Home Phone',
      badgeNumber: 'Badge Number',
      badgeNumberS: 'Badge',
      tempBadgeNumber: 'Temporary Badge Number',
      employeeCode: 'Employee Code',
      employeeCodeS: 'Code',
      seniorityDate: 'Seniority Date',
      seniorityDateS: 'Seniority',
      secondaryseniorityDate: 'Secondary Seniority Date',
      initiationDate: 'Initiation Date',
      miscDate: 'Misc Date',
      terminationDate: 'Termination Date',
      changeProfilePicture: 'Change your profile picture',
      groups: 'Groups',
      sin: 'Social insurance number (SIN)',
      birthDate: 'Date of birth',
      email: 'Email',
      hireInvitation: 'Hire and send an email invitation',
      hireManually: 'Hire and enter employee information manually',
      jobTitle: 'Job Title',
      recordType: 'Record Type',
      recordTypes: {
        EMPLOYEE: 'Employee',
        EMPLOYEE_TEMPLATE: 'Employee Template',
        CANDIDATE: 'Candidate',
        APPLICANT: 'Applicant',
        PAYEE: 'Payee',
      },
      blockAccess: 'Block Employee Access',
      blockProfileChanges: 'Block Profile Changes',
      empTemplateId: 'Employee Template',
      middleName: 'Middle Name',
      alias: 'Nickname',
      nickname: 'Nick Name',
      status: 'Status',
      isRegistered: 'Registered',
      hireAnEmployee: 'Hire an Employee',
      inviteNewUesr: 'Invite New User',
      assignGroup: 'Assign Group',
      sendEmail: 'Send Email',
      activeAccess: 'Active Access Of Employee',
    },
    personal: {
      personal: 'Personal',
      idNumbers: 'ID Numbers',
      birthday: 'Birthday',
      gender: 'Gender',
      paymentMethod: 'Payment Method',
      payStubs: 'Pay Stubs',
      maritalStatus: 'Marital status',
      employerBusinessNumberId: 'Employer Business Number',
    },
    address: {
      title: 'Address',
      address1: 'Address Line 1',
      address2: 'Address Line 2',
      city: 'City',
      postalCode: 'Postal Code',
      zipCode: 'Zip Code',
      country: 'Country',
      province: 'Province',
      state: 'State',
    },
    bankAccount: {
      title: 'Bank Account',
      branch: 'Branch Transit (5)',
      bank: 'Bank ID (3)',
      accountNumber: 'Account Number (7+)',
      chequeSpecimen: 'Cheque Specimen',
    },
    paymentMethod: {
      title: 'Payment Method',
    },
    education: {
      title: 'Education',
      highestlevelofEducation: 'Highest level of education',
      graduationDate: 'Graduation Date',
      country: 'Country',
      notes: 'Notes',
    },
    idNumbers: {
      idType: 'Type',
      idNumber: 'Number',
      issuedCountry: 'Issued Country',
    },
    digitalIds: {
      type: 'Type',
      expiryDate: 'Expiry Date',
      text: 'Text',
      types: {
        FACE_RECOGNITION: 'Face Recognition',
        FINGER_GEOMETRY: 'Finger Geometry',
        FINGERPRINT: 'Fingerprint',
        IRIS: 'Iris',
        OTHER: 'Other',
      },
    },
    nonResident: {
      title: 'Non-Resident',
      alertDate: 'Alert Date',
      visaExpiryDate: 'Visa Expiry Date',
      passportExpiryDate: 'Passport Expiry Date',
      statusReviewDate: 'Status Review Date',
      passportNumber: 'Passport Number',
      passportIssuingCountry: 'Passport Issuing Country',
      status: 'Status',
      visaNumber: 'Visa Number',
      visaType: 'Visa Type',
      note: 'Note',
    },
    preferences: {
      enum: {
        EMAIL: 'Email',
        SMS: 'SMS',
        PUSH: 'Push',
        NONE: 'None',
      },
      canAccess: {
        canAccssReimbursement: 'Expense reimbursment access',
        canAccessTimeEntry: 'Time entry access',
        canAccessTimeOff: 'Block access to Time Off entry',
        canAccessMyAvailability: 'Block access to My Availability',
        canAccessDocuments: 'Block access to Documents',
        canChangeBankAccount: 'Block Bank Account access',
        canChangeProfile: 'Can Change Profile',
        canAccessMobileTC: 'Block access to Mobile Time Collection',
        canLogin: 'Block login privilege',
        hasAccess: 'Block Employee Access',
        isProfileLocked: 'Block Profile Changes',
      },
      employeeBirthDay: 'Employee Birthday',
      newDocument: 'New Document',
      newSchedule: 'New Schedule',
      shiftEnd: 'Shift End',
      shiftStart: 'Shift Start',
      timeOffApproval: 'Time Off Approval',
      timeOffSubmittal: 'Time Off Submittal',
      timeSheetApproval: 'Time Sheet Approval',
      timeSheetSubmittal: 'Time Sheet Submittal',
      expenseReimbursementApproval: 'Expense Reimbursement Approval',
      expenseReimbursementSubmittal: 'Expense Reimbursement Submittal',
    },
    custom: {
      title: 'Custom',
    },
    contacts: {
      addContact: 'Add Contact',
      title: 'Contacts',
      contactsAndFamily: 'Contacts and Family',
      contact: 'Contact',
      relationship: 'Relationship',
      callSequence: 'Emergency Call Sequence',
      note: 'Note',
      callSequences: {
        0: 'No Priority',
        1: 'First',
        2: 'Second',
        3: 'Third',
      },
    },
    settings: {
      title: 'Settings',
      preferences: 'Preferences',
      preferredLanguage: 'Preferred Language',
      preferredDateFormat: 'Preferred Date Format',
      preferredTimeFormat: 'Preferred Time Format',
      preferredCurrency: 'Preferred Currency',
      notifications: 'Notifications',
      isTimeSheetApproval: 'Time Sheet Approval',
      isTimeSheetRejection: 'Time Sheet Rejection',
      isTimeSheetMessage: 'Time Sheet Message',
      isTimeOffApproval: 'Time Off Approval',
      isTimeOffRejection: 'Time Off Rejection',
      isNewDocument: 'New Document',
      asOfDate: 'As of Date : ',
    },
    payRate: {
      payRateAssign: 'Pay Rate',
      addPayRate: 'Add Pay Rate',
      editPayRate: 'Edit Pay Rate',
      payRateType: 'Pay Rate Type',
      payRate: 'Pay Rate',
      currency: 'Currency',
      paymentMethod: 'Payment Method',
      latestEffectiveDate: 'Latest Effective Date',
      asofdate: 'As of Date',
    },
    compensation: {
      standardhoursperday: 'Standard Hours Per Day',
      standardhoursperpay: 'Standard Hours Per Pay',
      excludeattendancehoursfrompay: 'Exclude Attendance Hours From Pay',
      secondaryPayRate: 'Secondary Pay Rate',
      prevEmployment: 'Previous Employment',
    },
    list: {
      bulkActions: 'Bulk Actions',
      hire: 'Hire',
      sendEmail: 'Send Email',
      assignEmployeeToTheGroup: 'Assign Employee to the Group',
      blockAccess: 'Block Access',
      activeAccess: 'Active Access',
      empsSelected: 'employee(s) selected.',
      effectiveDate: 'Effective Date',
      expiryDate: 'Expiry Date',
      dateBasedGroups: 'Date based groups',
      noExpiry: 'No Expiry',
      filters: 'Filters',
      resetColumns: 'Reset Columns',
    },
  },
  audit: {
    property: 'Property',
    path: 'Path',
    action: 'Action',
    date: 'Date',
    time: 'Time',
    user: 'User',
    from: 'From',
    to: 'To',
    batch: 'Batch',
  },
  events: {
    addEvent: 'Add Event',
    name: 'Name',
    status: 'Status',
    date: 'Date',
    location: 'Location',
    note: 'Note',
    hasRSVP: 'Has RSVP',
    statusEnum: {
      PENDING: 'Pending',
      APPROVED: 'Approved',
      CANCELLED: 'Cancelled',
      RESCHEDULED: 'Rescheduled',
    },
    isPublic: 'Is Public',
  },
  glaccounts: {
    addaccount: 'Add Account',
    accountNumber: 'Account Number',
    glType: 'GL Type',
    glEnum: {
      ASSET: 'Asset',
      EXPENSE: 'Expense',
      LIABILITY: 'Liability',
    },
    status: 'Status',
  },
  projects: {
    projects: 'Projects',
    addProject: 'Add Project',
    completed: 'Completed',
    leader: 'Leader',
    barCode: 'Bar Code',
    qrCode: 'QR Code',
    exportLink: 'Export Link',
    importLink: 'Import Link',
    status: 'Status',
    estimatedHours: 'Estimated Hours',
    esitmatedCost: 'Estimated Cost',
    note: 'Note',
    completedPercent: 'Completed Percent',
    timeBilling: 'Time Billing',
    workflowState: 'Workflow State',
    changedBy: 'Changed By',
    changedOn: 'Changed On',
    billingRate: 'Billing Rate',
    customerId: 'Customer ID',
    billingRateEnum: {
      FIXED_WORK: 'Fixed Work',
      FIX_EARNED: 'Fixed Earned',
      COST_PLUS_FEE: 'Cost Plus Fee',
      COST_PLUS_PERCENTAGE: 'Cost Plus Percentage',
      TIME_BANK: 'Time Bank',
    },
    prjStatus: {
      IN_PROGRESS: 'In Progress',
      ON_HOLD: 'On Hold',
      CANCELLED: 'Cancelled',
      COMPLETED: 'Completed',
    },
  },
  documents: {
    action: 'Action',
    date: 'Date',
    referenceNumber: 'Reference Number',
    fileName: 'File Name',
    description: 'Description',
    confirmdelete: 'Are you sure you want to delete this document?',
    note: 'Note',
    referenceDate: 'Reference Date',
    documentuploadedsuccess: 'Document uploaded successfully',
    documentuploadedfailed: 'Document upload failed',
    documentdeletesuccess: 'Document deleted successfully',
    documentdeletefailed: 'Document delete failed',
    clickordragfiletothisareatoupload: 'Click or drag file to this area to upload',
    youcanuploadonlyonefileperupload: 'You can upload only one file per upload',
  },
  availability: {
    eventmustbebefore12: 'Event must be before 12:00 AM',
    InvalidStartOrEndDate: 'Invalid Start or End Date',
    addEvent: 'Add an Event',
    UpdateorDeleteEvent: 'Update or Delete Event',
    StartToEnd: 'Start to End Range',
    date: 'Date',
    addBtn: 'Add',
    updateBtn: 'Update',
    delBtn: 'Delete',
    weekends: 'weekends',
    pickdate: 'Pick Date',
    refresh: 'Refresh',
    available: 'available',
    duration: 'Duration',
  },
  payitemsOrgPage: {
    filteroptions: 'Filter Options',
    empstatus: 'Employee Status',
    showactiveemponly: 'Status',
    empcode: 'Employee Code',
    hourly: 'Hourly',
    other: 'Other',
    piecework: 'Piecework',
    payitemstatus: 'Pay Item Status',
    stuborder: 'Stub Order',
    manual: 'Manual',
    payitemsOrgPage: 'Pay Items',
    isExcludeFromPayroll: 'Exclude From Payroll',
    payroll: 'Payroll',
    otheramount: 'Other Amount',
    shortcut: 'Shortcut',
    payitemalreadyexists: 'Pay item already exists',
    active: 'Active',
    inactive: 'Inactive',
    exempt: 'Exempt',
    importlinkcode: 'Import Link Code',
    exportlinkcode: 'Export Link Code',
    time: 'Time',
    doubletime: 'Double Time',
    othertime: 'Other Time',
    timeoff: 'Time Off',
    vacation: 'Vacation',
    statutoryholiday: 'Statutory Holiday',
    break: 'Break',
    // overtime: 'Overtime',
    regulartime: 'Regular Time',
    expense: 'Expense',
    absence: 'Absence',
    work: 'Work',
    memos: 'Memos',
    accruals: 'Accruals',
    reimbursements: 'Reimbursements',
    employerContributions: 'Employer Contributions',
    deductions: 'Deductions',
    earnings: 'Earnings',
    entrymethod: 'Entry Method',
    entryType: 'Entry Type',
    category: 'Category',
    reportingcode: 'Reporting code',
    assignedpayitems: 'Assigned Pay Items',
    editpayitem: 'Edit Pay Item',
    balance: 'Balance',
    rate: 'Rate',
    name: 'Name',
    add: 'Add',
    save: 'Save',
    close: 'Close',
    status: 'Status',
    description: 'Description',
    type: 'Type',
    overtime: 'Overtime Eligible',
    contribute: 'Contribute to holiday time',
    chargeable: 'Chargeable',
    paidfrombank: 'Paid from Bank',
    paidfromamountbank: 'Paid from Amount Bank',
    paidfromtimebank: 'Paid from Time Bank',
    showbalance: 'Block Balance Display',
    displayorder: 'Display Order',
    yes: 'Yes',
    no: 'No',
    attendancecat: 'Default Attendance Category',
    assigntogroups: 'Assign to Groups',
    payitems: 'Pay Items',
    payitem: 'Pay Item',
    employees: 'Employees',
    notes: 'Notes',
    Available: 'available',
    Selected: 'selected',
    enterdescription: 'Pay Item Description',
    selectvalue: 'Select a Value',
    selectattendance: 'Select Attendance Category',
    addpayitem: 'Add Pay Item',
    updatepayitem: 'Pay Item',
    payitemdeleted: 'Payitem Deleted',
    payitemadded: 'Payitem Added',
    payitemupdated: 'Payitem Updated',
    payitemassignedtogroups: 'Payitem Assigned to Groups',
    payitemassignedtoemployees: 'Payitem Assigned to Employees',
    payitemunassignedfromemployees: 'Payitem Unassigned from Employees',
    assignpayitem: 'Assign Payitem',
    unassignpayitem: 'Unassign Payitem',
    updateassignedpayitem: 'Update Assigned Payitem',
    selectpayitemstoadd: 'Select Payitems to add',
  },
  payitemsGroupPage: {
    namealreadyexists: 'Name already exists',
    codealreadyexists: 'Code already exists',
    systemNotes: 'System notes',
    note: 'Note',
    code: 'Code',
    isactive: 'Active',
    issystem: 'System',
    isReportUse: 'Use for reports',
    Actions: 'Actions',
    required: 'Required',
    enterPayitem: 'Enter payitem group',
    enterCode: 'Enter Code',
    payitemgroup: 'Pay Item Group',
    payitemgroups: 'Pay Item Groups',
    addpayitemgroup: 'Add Payitem Group',
    updatepayitemgroup: 'Pay Item Group',
    payitemgroupadded: 'Payitem Group Added',
    payitemgroupupdated: 'Payitem Group Updated',
  },
  attendancecategories: {
    attendancecategory: 'Attendance Category',
    name: 'Name',
    add: 'Add',
    save: 'Save',
    close: 'Close',
    notes: 'Notes',
    AttendanceType: 'Attendance Type',
    addattendancecategory: 'Add Attendance Category',
    updateattendancecategory: 'Update Attendance Category',
    attendancecategorieupdated: 'Attendance Category Updated',
  },
  holidayCalendar: {
    assignedholidaycalendar: 'Assigned Holiday Calendar',
    holidayCalendar: 'Holiday Calendar',
    name: 'Name',
    namerequried: 'Name is required',
    employees: 'Employees',
    addholidaycalendar: 'Add Holiday Calendar',
    updateholidaycalendar: 'Update Holiday Calendar',
    assigntoemployees: 'Assign to Employees',
    updateholiday: 'Update Holiday',
    addaholiday: 'Add a Holiday',
    updateordeleteholiday: 'Update or Delete Holiday',
    holidayadded: 'Holiday Added',
    holidayupdated: 'Holiday Updated',
    holidaydeleted: 'Holiday Deleted',
    allcalendars: 'Holiday Calendars',
    gotocalendar: 'Calendar View',
    notes: 'Notes',
    clonecalendar: 'Copy Calendar',
    totalholidays: 'Holidays',
    importfromexistingcalendar: 'Import from Existing Calendar',
    EnableConditionsforthisholiday: 'Enable Conditions for this Holiday',
    dateisrequired: 'Date is required',
  },
  holidayConditions: {
    holidayConditions: 'Holiday Conditions',
    minimumSeniority: 'Minimum Seniority',
    Employment: 'Employment',
    holidayMustFallOnAScheduledWorkDay: 'Holiday must fall on a scheduled workday',
    Employeenotabsentonthedaybeforetheholiday: 'Employee not absent on the day before the holiday',
    Employeenotabsentonthedayaftertheholiday: 'Employee not absent on the day after the holiday',
    Employeenotabsentonthelastscheduledworkdaybeforetheholiday:
      'Employee not absent on the last scheduled workday before the holiday',
    Employeenotabsentonthelastscheduledworkdayaftertheholiday:
      'Employee not absent on the last scheduled workday after the holiday',
    workedatleast: 'Worked at least',
    daysinthelast: 'days in the last',
    monthsbeforeholiday: 'months before holiday',
    daysbeforeholiday: 'days before holiday',
    calendardaysinthelast: 'Calendar days in the last',
    Workedthatdayoftheweek: 'Worked that day of the week',
    timesinthelast: 'times in the last',
    EmploymentshouldbeAtleast: 'Employment should be at least',
    calendardaysinthe: 'calendar days in the',
    monthspriortotheholiday: 'months prior to the holiday',
    seniority: 'Seniority',
    employment: 'Employment',
    work: 'Work',
  },
  groups: {
    notExpiredFound: 'Not Expired Group Found',
    pleaseExpireLastAssignment: 'Please Expire Last Assignment',
    overlapDetected: 'Overlap Detected',
    groups: 'Groups',
    name: 'Name',
    assignedgroup: 'Groups',
    assigngroup: 'Assign Group',
    unassigngroup: 'Unassign Group',
    confirmdelete: 'Are you sure you want to delete this group?',
    managers: 'Managers',
    create: 'Create',
    createGroup: 'Create Group',
    group: 'Group',
    createGroupType: 'Create Group Type',
    wF: 'Workflow',
    clientCode: 'Code',
    comment: 'Comment',
    note: 'Note',
    conflicts: 'Conflicts!',
    wishToReplace: 'Do you wish to replace?',
    isAlreadyAssigned: 'is already assigned to',
    someSelectedEmployeesAreAlreadyAssigned: 'Some selected employees are already assigned.',
    createGroupFor: 'Create New ',
    updateGroupOf: 'Update Group of',
    tableHeaders: {
      groupName: 'Group Name',
      groupType: 'Group Type',
      numberOfEmployees: 'Employees',
      numberOfManagers: 'Managers',
      primaryManager: 'Primary Manager',
      primary: 'Primary',
      actions: 'Actions',
    },
    tabs: {
      generalInfo: 'General Information',
      documents: 'Documents',
      properties: 'Properties',
      employees: 'Employees',
    },
  },
  workPlans: {
    address: 'Address',
    coordinatesText: 'Coordinates',
    addressLine1: 'Address Line 1',
    addressLine2: 'Address Line 2',
    searchLocation: 'Search for a location',
    alertPeriod: 'Alert Period (days)',
    alias: 'Alias',
    legalName: 'Legal Name',
    availabilityNumber: 'Number of Positions Available',
    benefitOptions: 'Benefit Options',
    classes: 'Classes',
    BIWEEKLY: 'Biweekly',
    businessNumberFederal: 'Federal Business Number',
    businessNumbers: 'Business Number',
    businessNumberQuebec: 'Business Number Quebec',
    businessType: 'Business Type',
    cCQNumber: 'CCQ Number',
    city: 'City',
    clientCode: 'Code',
    closePayWF: 'Close Pay',
    contact: 'Contact',
    contactEmail: 'Contact Email',
    contactExtension: 'Extension',
    contactLanguage: 'Contact Language',
    contactName: 'Contact Name',
    contactPhone: 'Contact Phone',
    coordinates: { lat: 'Latitude', lng: 'Longitude' },
    country: 'Country',
    currency: 'Currency',
    linkCode: 'Link Code',
    internalJobListingStatus: 'Internal Job Listing Status',
    thirdPartyJobListingStatus: '3rd Party Job Listing Status',
    jobListingStatus: {
      open: 'Open',
      close: 'Close',
    },
    trainingIds: 'Trainings',
    successionPlanWFId: 'Succession Plan Workflow',
    successionPlanNote: 'Succession Plan Note',
    eE: 'EE Occupation group',
    eEO: 'EEO Job Categories',
    eFTAccounts: 'Credit Bank Accounts',
    eIn: 'Empoyer Identification Number',
    employeeRecordChangeWF: 'Employee record change',
    expenseWF: 'Expense',
    experienceYears: 'Experiance (years)',
    federalDepositSchedule: 'Federal Deposit Schedule',
    federalTransmitterNumber: 'Federal Transmitter Number',
    fiscalYearEndDay: 'Fiscal Year End Day',
    fiscalYearEndMonth: 'Fiscal Year End Month',
    FOUR_WEEKS: 'Four Weeks',
    gLAccountID: 'G/L Account',
    hiringLeadId: 'Hiring Lead',
    incomeTaxForm: 'Income Tax Form',
    isActive: 'Active',
    isAllowSchedule: 'Block Employee `My Team Schedule` display',
    isAllowTeamTracker: 'Block Employee `My Team Tracker` display',
    isClosed: 'Closed',
    isPrimary: 'Primary',
    issuedBy: 'Issued By',
    issuePayChequesWF: 'Issue pay cheques',
    issuePayDirectDepositsWF: 'Issue pay direct deposits',
    level: 'Levels',
    location: 'Location',
    locationBy: 'Location By',
    logo: 'Logo',
    maxSalary: 'Maximum Salary',
    memberDescription: 'Member Description',
    minSalary: 'Minimum Salary',
    MONTHLY: 'Monthly',
    name: 'Name',
    qcOrFederal: 'Quebec or Federal',
    QC: 'Quebec',
    FEDERAL: 'Federal',
    nameTranslate: 'Name',
    nextSeqNumber: 'Next Seq Number',
    nOC: 'NOC Occupation Title',
    employeeAssignmentProfile: 'Employee Assignment Properties',
    contactInformation: 'Contact Information',
    ntfyPriorDays: 'Notification preior date',
    ntfyTime: 'Notification time',
    ntfyTimeZone: 'Notification time zone',
    offBoardingWF: 'Employee Offboarding',
    onBoardingWF: 'Employee Onboarding',
    pADAccounts: 'Debit Bank account',
    payCalendar: 'Pay Calendar',
    payDate: 'Pay Date',
    payFrequency: 'Pay Frequency',
    payItems: 'Pay Items',
    payRaiseWF: 'Pay Raise',
    payrollYear: 'Payroll Year',
    performanceReviewWF: 'Performance Review',
    periodEndDate: 'Period End Date',
    periodStartDate: 'Period Start Date',
    phone: 'Phone',
    picture: 'Picture',
    planUrl: 'Plan URL',
    policyNumber: 'Policy Number',
    positionApprovalWF: 'Position Approval',
    postalCode: 'Postal Code',
    zip: 'Zip',
    posting: 'Position Posting',
    probationDays: 'Probation Days',
    probationMonths: 'Probation Months',
    proficiencies: 'Proficiencies',
    proficienciesList: 'Proficiencies List',
    proprietor1: 'Proprietor 1 SIN',
    proprietor2: 'Proprietor 2 SIN',
    providerName: 'Provider Name',
    province: 'Province',
    quebecTransmitterNumber: 'Quebec Transmitter Number',
    remitFrequency: 'Remit Frequency',
    remitFrequencyFederal: 'Remit Frequency Federal',
    remitFrequencyQuebec: 'Remit Frequency Quebec',
    renewalFrequency: 'Renewal frequency (months)',
    transmitterNumbers: 'Transmitter Numbers',
    t4aRpp: 'Pension Accounts',
    rRRDPSP: 'RPP / DSSP Account',
    t4APensionAccount: 'T4A Pension Account',
    transmitterNumber: 'Transmitter Number',
    reportingToId: 'Reporting to',
    reviewFrequency: 'Review Frequency (months)',
    reviewTemplate: 'Review Template',
    SEMI_MONTHLY: 'Semi Monthly',
    sequence: 'Sequence',
    skill: 'Skill',
    skills: 'Required Skills',
    startDate: 'Start Date',
    step: 'Steps',
    sUITax: 'State Unemployment Insurance (SUI) tax',
    taxWithholdingCountry: 'Tax Withholding Country',
    timeOffRequestWF: 'Time-off',
    timeSheetPayrollSubmitWF: 'Timesheet payroll submittal',
    timeSheetWF: 'Timesheet',
    transitNumber: 'Transit Number',
    WEEKLY: 'Weekly',
    workPlanPublishDate: 'Latest Schedule Publish Date',
    jobDescription: 'Job Description',
    stateIdNo: {
      state: 'State Name',
      idNumber: 'State Id',
    },
    account: {
      bank: 'Bank',
      branch: 'Branch',
      accountNumber: 'Account Number',
    },
    proficienciesOptions: {
      irrelevant: 'Irrelevant',
      poor: 'Poor',
      bellow: 'Bellow',
      average: 'Average',
      good: 'Good',
      below_average: 'Below Average',
      excellent: 'Excellent',
      IRRELEVANT: 'Irrelevant',
      POOR: 'Poor',
      BELOW: 'Bellow',
      AVERAGE: 'Average',
      GOOD: 'Good',
      EXCELLENT: 'Excellent',
    },
    options: {
      none: 'No approval required',
      levelOne: 'One approval level',
      levelTwo: 'Two approval level',
    },
    unionTabs: {
      unionStatuses: 'Union Status',
      tradeCodes: 'Trade Codes',
      sectors: 'Sectors',
      categories: 'Categories',
      regions: 'Reigons',
      wages: 'Wage Schedule',
    },
  },
  groupTypes: {
    groupTypes: 'Group Types',
    groupTypeName: 'Name',
    addressUsed: 'Address Used',
    isDateSensitive: 'Date Sensetive',
    isDateSensitives: {
      A: 'Yes with Effective Dates Only',
      N: 'No',
      Y: 'Yes with Expiry Dates',
    },
    color: 'Color',
    datedEmployeeAssignment: 'Dated Employee Assignments',
    allowMultipleEmployeeAssignment: 'Allow Multiple Employee Group Assignments',
    systemType: 'System Type',
  },
  groupSystemTypes: {
    TEAM: 'Team',
    DEPARTMENT: 'Department',
    POLICY: 'Policy',
    WORKPLAN: 'Work plan',
    PAYGROUP: 'Pay group',
    SITE: 'Site',
    UNION: 'Union',
    EMP_TYPE: 'Employment Type',
    LOCATION: 'Location',
    POSITION: 'Position',
    EMP_STATUS: 'Employment Status',
    EMPLOYER: 'Employer',
    PAY_CALENDAR: 'Pay Calendar',
    BENEFIT: 'Benefit Plan',
    SKILL: 'Skill',
    LICENSE: 'Licence',
    PERMIT: 'Permit',
    OTHER: 'Other',
  },
  supervisors: {
    organization: 'Organization',
    profile: 'Profile',
    menuProfile: 'Menu Profile',
    isPrimarySupervisor: 'Primary Supervisor',
    isPrimaryManager: 'Primary Manager',
    createAndModifyPunches: 'Create & Modify Punches',
    temporaryOnboarding: 'Temporary Onboarding',
    timeSheetApproval: 'Timesheet Approval',
    timeOffRequestApproval: 'Time-off Request Approval',
    expenseReimbursementApproval: 'Expense Reimbursement Approval',
    employeeProfiles: 'Employee Profiles',
    employeeTemplates: 'Employee Templates',
    applicantsAndCandidates: 'Applicante and candidates',
    employeePayStubs: 'Employee Paystubs',
    employeeTimeSheet: 'Employee Timesheets',
    employeeConfidentialInformation: 'Employee Confidential Information',
    employeeSchedules: 'Employee Schedules',
    employeeExpenseReimbursement: 'Employee Expense Reimbursements',
    employeePayRates: 'Employee Pay Rates',
    performanceReviews: 'Performance Reviews',
    EmployeeTimeOffRequests: 'Employee Time-off Requests',
    timeSheetSubmittal: 'Timesheet Submittal',
    timeOffRequestSubmittal: 'Time-off Request Submittal',
    expenseReimbursementSubmittal: 'Expense Reimbursement Submittal',
    issuePayChequeApprovalLevelEnum: 'Issue Pay Cheques Approval',
    issuePayDirectDepositApprovalLevelEnum: 'Issue Pay Direct Deposits Approval',
    accessTemplate: 'Employee Templates',
    closePayApprovalLevelEnum: 'Close Pay Approval',
    payItems: 'Pay Items',
    actions: 'Actions',
    onBoard: 'Onboard',
    offBoard: 'Offboard',
    invite: 'Invite',
    both: 'Both',
    onboardApproval: 'Onboard Approval',
    offboardApproval: 'Offboard Approval',
    performanceApproval: 'Performance Reviews Approval',
    positionApproval: 'Position Changes Approval',
    accessPosition: 'Position Change',
    onboardNtfy: 'Onboard Submittal',
    offboardNtfy: 'Offboard Submittal',
    performanceNtfy: 'Performance Reviews Submittal',
    positionNtfy: 'Position Change Submittal',
    closePayNtfyLevel: 'Close Pay Notification',
    issuePayDirectDepositNtfyLevel: 'Issue Pay Direct Deposit',
    issuePayChequeNtfyLevel: 'Issue Pay Cheques',
    onboardOffboard: 'Onboarding / Offboarding',
    accessCalendar: 'Pay and Holiday Calenders',
    menuTemplate: 'Menu Template',
    selectMenuTemplate: 'Select a menu template',
    tabs: {
      permissions: 'Permissions',

      authorityLevel: 'Authority Level',
      accessLevel: 'Access Level',
      notificationLevel: 'Notification Level',
    },
    placeholders: {
      select: 'Select',
    },
    options: {
      none: 'None',
      all: 'All',
      hide: 'Hide',
      view: 'View',
      modify: 'Modify',
      create: 'Create',
      delete: 'Delete',
      levelOne: 'Level One',
      levelTwo: 'Level Two',
    },
  },
  modals: {
    createGroupType: 'Create Group Type',
    updateGroupType: 'Update Group Type',
    createGroup: 'Create Group',
    updateGroup: 'Update Group',
    createSupervisor: 'Create Manager',
  },
  form: {
    general: {
      fieldisrequired: 'This field is required',
      submit: 'Submit',
      save: 'Save',
      name: 'Name',
      note: 'Note',
      clientcode: 'Client Code',
      reportingcode: 'Reporting Code',
      displaysequence: 'Sequence',
      mandatory: 'Mandatory',
      active: 'Active',
      inactive: 'Inactive',
      geoposition: 'Geo Position',
      saveIsDisabled: 'Save Is Disabled',
      all: 'All',
    },
    group: {
      general: {
        name: 'Name',
        groupType: 'Type',
        parentGroup: 'Parent Group',
      },
      team: {
        expenseWF: 'Expense workflow',
        timeSheetPayrollSubmitWF: 'Timesheet payroll submittal workflow',
        timeSheetWF: 'Timesheet workflow',
        timeOffRequestWF: 'Time-off workflow',
      },
      department: {
        offBoardingWF: 'Employee Offboarding workflow',
        onBoardingWF: 'Employee Onboarding workflow',
        payRaiseWF: 'Pay Raise workflow',
        positionApprovalWF: 'Position Approval workflow',
        recordChangeWF: 'Employee record change workflow',
      },
      paygroup: {
        closePayWF: 'Close Pay workflow ',
        issuePayChequesWF: 'Issue Pay Direct Deposits workflow',
        issuePayDirectDepositsWF: 'Issue Pay Cheques workflow ',
      },
      address: {
        addressLine1: 'Address 1',
        addressLine2: 'Address 2',
        city: 'City',
        country: 'Country',
        location:
          'GPS coordinates / Choose Address ID Internet to enter or view Internet information',
        phone: 'Phone ',
        picture: 'Picture',
        postalCode: 'Zip code / Postal code',
        province: 'State / Province',
      },
      workPlan: {
        effectiveDate: 'Effective Date',
        rotationPeriod: 'Rotation Period',
        publishDateTime: 'Publish Date Time',
        capacity: 'Capacity',
        preview: 'Preview',
        day: 'Day',
        unAttendanceThreshold: 'Unscheduled attendance threshold',
        unAttendanceRounding: 'Unscheduled attendance and Flex time rounding rule',
        unAttendance: 'Default unscheduled rounding',
        workPlanpreview: 'WorkPlan Preview',
      },
    },
  },
  notification: {
    success: {
      add: 'Item Sucessfully Added',
      update: 'Item Sucessfully Updated',
      delete: 'Item Sucessfully Removed',
      assignmentUpdate: 'Assignmnet Sucessfully Updated',
    },
  },
  trackingsegments: {
    restrictedTrackingItems: 'Restricted Tracking Items',
    defaultTrackingItem: 'Default Tracking Item',
    assigntrackingsegment: 'Assign Tracking Segment',
    assignedTrackingSegments: 'Assigned Tracking Segments',
    displaysequence: 'Display Sequence',
    trackingitemsfor: 'Tracking Items for',
    itemswillberemoved: 'Items will be removed',
    bulkdeletetrackingitems: 'Bulk Delete Tracking Items',
    viewtrackingitems: 'View Tracking Items',
    addtrackingsegment: 'Add Tracking Segment',
    updatetrackingsegment: 'Tracking Segment',
    addtrackingitem: 'Add Tracking Item',
    updatetrackingitem: 'Update Tracking Item',
    trackingsegments: 'Tracking Segments',
    type: 'Type',
    validationlistdisplay: 'Display Choice',
    validationlistdisplaytype: 'Display Choice',
    validationmethod: 'Validation',
    freeform: 'Freeform',
    grouptype: 'Group Type',
    logical: 'Logical',
    integer: 'Integer',
    numeric: 'Numeric',
    list: 'List',
    jira: 'Jira',
    position: 'Position',
    project: 'Project',
    code: 'Code',
    name: 'Name',
    both: 'Name and Code',
  },
  assets: {
    assets: 'Assets',
    assignments: 'Assignments',
    assignmentsOf: 'Assignments of',
    createAsset: 'Create Asset',
    editAsset: 'Edit Asset',
    isActive: 'Active',
    assetName: 'Name',
    note: 'Note',
    code: 'Code',
    linkCode: 'Link Code',
    serialNo: 'Serial Number',
    config: 'Configuration',
    vendor: 'Vendor',
    purchaseDate: 'Purchase Date',
    cost: 'Cost',
    currency: 'Currency',
    dueDatePeriod: 'Due Date Alert Period',
    nextScheduleDate: `Next Scheduled Maintenance Date`,
    action: 'Action',
    contact: 'Contact',
    contactName: 'Contact Name',
    contactPhone: 'Contact Phone',
    contactEmail: 'Contact Email',
    properties: 'Properties',
    documents: 'Documents',
    employeeAssignment: 'Employee Assignment',
    assignAssetToEmployee: 'Assign Asset To Employee',
    employee: 'Employee',
    issueDate: 'Issue Date',
    dueDate: 'Due Date',
    returnDate: 'Return Date',
    status: 'Status',
    onlyShowAvailableAssets: 'Only Show Available Assets',
    createAssset: 'Create Asset',
    updateAsset: 'Edit Asset',
    createAssignment: 'Create Assignment',
    updateAssignment: 'Edit Assignment',
    setReturnDateToToday: 'Set Return Date to Today',
    image: 'Image',
    addEmployee: 'Add Employee(s)',
    assignAsset: 'Assign Asset',
    issueHistory: ' - Issue History',
    overdueAsset: 'Overdue Asset',
    dueAfterIssue: 'Due date should be later issue date',
    returnAfterIssue: 'Return date should be later issue date',
    editAssignment: 'Edit Asset Assignemnt',
  },
  performance: {
    list: 'List',
    month: 'Month',
    week: 'Week',
    at: 'at',
    addPerformanceReview: 'Add Performance Review',
    editPerformanceReview: 'Edit Performance Review',
    reviewStatus: 'Status',
    reviewDate: 'Review Date/Time',
    period: 'Review Period (months)',
    duration: 'Duration (minutes)',
    evaluatorProfile: 'Evaluator',
    employeeProfile: 'Employee',
    location: 'Review Location',
    alertInDays: 'Review Alert (days)',
    alertInMinutes: 'Review Alert (minutes)',
    positionGroup: 'Position',
    reviewScore: 'Review Score',
    general: 'General',
    scores: 'Scores',
    performanceReviewCategory: 'Category',
    score: 'Score',
    note: 'Note',
    action: 'Action',
    evaluatorNote: 'Evaluator',
    employeeNote: 'Employee',
    signature: 'Signature',
    reviewFor: 'Review For ',
    reviewBy: 'Review By',
    latestEvaluation: 'Latest Evaluation (date)',
    attachments: 'Attachments',
    reviewWf: 'Review Workflow',
    wfStatus: 'Workflow Status: ',
    reviewStatuses: {
      TBD: 'TBD',
      WF: 'Workflow',
      PROPOSED: 'Proposed',
      DRAFT: 'Draft',
      INVITE: 'Invited',
      ACKNOWLEDGED: 'Acknowledged',
      PENDING: 'Pending',
      COMPLETED: 'Completed',
      ON_HOLD: 'On Hold',
      FOLLOW_UP: 'Follow Up',
    },
  },
  training: {
    profile: 'Profile',
    sign: 'Signature',
    addAssignment: 'Add Assignment',
    actions: 'Actions',
    issueDate: 'Issue Date',
    evaluation: 'Evaluation',
    dueDate: 'Due Date',
    fullName: 'Full Name',
    trainingStatus: 'Training Status',
    completionDate: 'Completion Date',
    assign: 'Assign',
    assignmentsOf: 'Assignments of ',
    addTraining: 'Add Training',
    code: 'Code',
    name: 'Name',
    linkCode: 'Link Code',
    status: 'Status',
    active: 'Active',
    note: 'Note',
    // urlList: 'URL List & Credentials',
    urlList: 'URL List',
    url: 'URL',
    assignedTo: 'Employees',
    general: 'General',
    documents: 'Documents',
    recurrence: 'Recurrence (months)',
    reqSign: 'Require Employee Signature',
    createTraining: 'Create Training',
    updateTraining: 'Update Training',
    signed: 'Signed',
  },
  languages: {
    EN: 'English',
    FR: 'French',
    'hr-IL': 'Hebrew',
  },
  monthsInNum: {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December',
  },
  signer: {
    clickToSign: 'Click to sign',
    removeSign: 'Remove Signiture',
    signedOn: 'Signed on',
    signedBy: 'Signed by',
  },
  breadcrumbs: {
    dashboard: 'Dashboard',
    customers: 'Customers',
    attendance: 'Attendance',
    projects: 'Projects',
    teams: 'Teams',
    availability: 'Availability',
    organization: 'Organization',
    settings: 'Settings',
    calendars: 'Calendars',
    event: 'Event',
    holiday: 'Holiday',
    trackingsegments: 'Tracking Segments',
    locations: 'Locations',
    assets: 'Assets',
    union: 'Union',
    advance: 'Advance',
    employmentTypes: 'Employment Types',
    employmentStatuses: 'Emplyment Statuses',
    wF: 'Workflow',
    assignments: 'Assignments',
    notificationsTemplates: 'Notifications Templates',
    employees: 'Employees',
    departments: 'Departments',
    employeeGroups: 'Employee Groups',
    chart: 'Organizational Chart',
    performanceReview: 'Performance Review',
    positions: 'Positions',
    benefitPlans: 'Benefit Plans',
    licensesAndPermits: 'Licenses and Permits',
    applicantAndCandidates: 'Applicants & Candidates',
    employeetemplates: 'Employee Templates',
    skills: 'Skills',
    workflow: 'Workflow',
    training: 'Training',
    pay: 'Pay',
    employer: 'Employer',
    payGroups: 'Pay Groups',
    payItems: 'Pay Items',
    payItemGroups: 'Pay Item Groups',
    payees: 'Payees',
    timeOffRequests: 'Time-off Requests',
    glaccounts: 'GL Accounts',
    workPlans: 'Work Plans',
    dayDefinitions: 'Day Definitions',
    payCalendar: 'Pay Calendar',
    onboarding: 'Onboarding',
    offboarding: 'Offboarding',
  },
  wF: {
    wF: 'Workflow',
    wFTransition: 'Workflow Transitions',
    transitionFrom: 'Transition from',
    noStateError: 'Please add at least one state',
    status: 'Status',
    active: 'Active',
    name: 'Name',
    type: 'Type',
    actions: 'Actions',
    transitions: 'Transitions',
    steps: 'Steps',
    actionList: 'Action List',
    note: 'Note',
    contacts: 'Contacts',
    general: 'General',
    updateWF: 'Update Workflow',
    addWF: 'Add Workflow',
    contactProfileOne: 'Contact 1',
    contactProfileTwo: 'Contact 2',
    fromStatus: 'From Status',
    toStatus: 'To Status',
    tasks: 'Tasks',
    task: 'Task',
    nt: 'Notification Template',
    checklist: 'Checklist',
    assign: 'Assign',
    addTransition: 'Add Transition',
    updateTransition: 'Update Transition',
    fullName: 'Full Name',
    profile: 'Profile',
    effectiveDate: 'Effective Date',
    state: 'State',
    fromState: 'From State',
    toState: 'To State',
    addChecklist: 'Add Checklist',
    assigned: 'Assigned!',
    unassigned: 'Unassigned!',
    moveToNextStep: 'Move to Next Step',
    types: {
      ONBOARDING: 'Onboarding',
      OFFBOARDING: 'Offboarding',
      REVIEW: 'Performance Review',
    },
    noChecklist: 'No Checklist!',
    noTransition: 'No Transition!',
    moveFrom: 'Move From',
    to: 'To',
    setTo: 'Set To',
    logs: 'Logs',
    logsFor: 'Logs for ',
    user: 'User: ',
    undoLastTransition: 'Undo Last Transition',
    wantToRunAction: 'Do you want to run this action from current state to previous?',
    yesRunActions: 'Yes, run actions',
    noDeleteLastTransition: 'No, delete last transition',
    actionsFiredSuccessfully: ' Actions Fired Successfully!',
    checklistStatuses: {
      PENDING: 'Pending',
      COMPLETED: 'Completed',
      NA: 'Not Applicable',
    },
    defaultStates: {
      START: 'Start',
      IN_PROGRESS: 'In Progress',
      CANCELLED: 'Cancelled',
      REJECTED: 'Rejected',
      ON_HOLD: 'On Hold',
      FOLLOW_UP: 'Follow Up',
      COMPLETED: 'Completed',
    },
    actionsList: {
      ACTIVATE_PROFILE: 'Activate Profile',
      DEACTIVATE_PROFILE: 'Deactivate Profile',
      EMP_STATUS_PART_TIME: 'Employee Status - Part Time',
      EMP_STATUS_FULL_TIME: 'Employee Status - Full Time',
      EMP_STATUS_CASUAL: 'Employee Status - Casual',
      EMP_STATUS_CONTRACT: 'Employee Status - Contract',
      EMP_STATUS_STUDENT: 'Employee Status - Student',
      EMP_STATUS_ONBOARD: 'Employee Status - Onboarding',
      EMP_STATUS_TERMINATED: 'Employee Status - Terminated',
      NOTIFY_EMP: 'Notify Employee',
      NOTIFY_SUPERVISOR: 'Notify Supervisor',
      NOTIFY_HR_MANAGER: 'Notify HR Manager',
      NOTIFY_PAY_MANAGER: 'Notify Pay Manager',
      NOTIFY_CONTACT1: 'Notify Contact 1',
      NOTIFY_CONTACT2: 'Notify Contact 2',
      RESET: 'Reset',
    },
    createWfWithTypeOnboarding: 'Please create at least one workflow woth type of Onboarding',
    noCheckList: 'No Check list',
    youCanMove: 'You Can Move!',
    direction: 'Direction',
    date: 'Date',
  },
  templates: {
    addNewTemplate: 'Add New Template',
    general: 'General',
    name: 'Name',
    templateType: 'Template Type',
    INVITATION: 'Invitation',
    HIRE: 'Hire',
    EMPLOYEE_WELCOME: 'Employee Welcome',
    EMAIL_TO_EMPLOYEE: 'Email to Employee',
    active: 'Active',
    note: 'Note',
    email: 'Email',
    htmlMessage: 'HTML Message',
    placeholders: 'Placeholders',
    clickAndPaste: 'Click and Paste above',
    sms: 'SMS',
    smsMessage: 'SMS Message',
    pushNotification: 'Push Notification',
    status: 'Status',
    isSystem: 'System',
    action: 'Action',
    addTemplate: 'Add Notification Template',
    employeeFirstName: 'Employee First Name',
    employeeLastName: 'Employee Last Name',
    supervisorFirstName: 'Supervisor First Name',
    supervisorLastName: 'Supervisor Last Name',
    managerFirstName: 'Manager First Name',
    managerLastName: 'Manager Last Name',
    date: 'Date',
    dateAsText: 'Date as Text',
    timeAmPm: 'Time (AM/PM)',
    time24h: 'Time (24h)',
    companyName: 'Company Name',
    companyLogo: 'Company Logo',
    copied: 'Copied!',
  },
  applicant: {
    type: 'Type',
    rank: 'Rank',
    status: 'Status',
    jobTitle: 'Job Title',
    position: 'Position',
    firstName: 'First Name',
    lastName: 'Last Name',
    personalPhone: 'Personal Phone, Cell',
    personalEmail: 'Personal Email',
    cvAttachment: 'CV Attachment',
    coverLetter: 'Cover Letter',
    email: 'Email',
    fullName: 'Full Name',
    active: 'Active',
    progress: 'Progress',
    actions: 'Actions',
    general: 'General',
    emailTemplate: 'Email Template',
    saveAndGoTo: 'Save and go to ',
    pleaseSelectTemplate: 'Please Select a template',
    addApplicant: 'Add Applicant',
    wfId: 'Workflow',
    APPLICANT: 'Applicant',
    CANDIDATE: 'Candidate',
    wfStatus: 'Workflow',
    employer: 'Employer',
    applicationStatus: 'Application Status',
    firstSave: 'Please first save the documnet and then try',
    department: 'Department',
  },
  uploader: {
    title: 'Click or drag file(s) to this area to upload',
    subtitle:
      'Support for a single or bulk upload. Strictly prohibit from uploading company data or other band files',
    sync: 'Sync Documnets',
    singleTitle: 'Click to upload',
    fileName: 'File Name',
    note: 'Note',
    description: 'Description',
    download: 'Download',
    preview: 'Preview',
    cancel: 'Cancel',
    filePreview: 'File Preview',
    uploadedBy: 'Uploaded By ',
    on: 'On ',
  },
  timeOffRequests: {
    employeeName: 'Employee Name',
    actions: 'Actions',
    status: 'Status',
    duration: 'Duration',
    days: 'days',
    day: 'day',
    Days: 'Days',
    minutes: 'Minutes',
    hours: 'hours',
    start: 'Start',
    end: 'End',
    submissionDate: 'Submission Date',
    fullDay: 'Full Day',
    partialDay: 'Partial Day',
    rangeOfDates: 'Range Of Dates',
    periodType: 'Period Type',
    payItem: 'Pay Item',
    note: 'Note',
    date: 'Date',
    startTime: 'Start Time Of Request',
    endTime: 'End Time of Request',
    dateRange: 'Date Range',
    cancel: 'Cancel Request',
    timeOffRequest: 'Time Off Request',
    all: 'All Teams',
    filters: 'Filters',
    buttons: {
      approve: 'Approve',
      unApprove: 'Un-approve',
      reject: 'Reject',
      cancel: 'Cancel',
      timeEntry: 'Time Entry',
    },
    employee: 'Employee',
    attendancePolicy: 'Attendance Policy',
    requestStatus: 'Request Status',
    absencePayItem: 'Employee absence pay items',
    cancelTitle: 'Cancel Timeoff requests',
    month: 'Month',
    week: 'Week',
    Day: 'Day',
    list: 'List',
    addNote: 'Add Note',
  },
  dayDefinitions: {
    start: 'Start Time',
    end: 'End Time',
    payItem: 'Pay Item',
    isExpectedIn: 'Is Expected In',
    addDif: 'Add Day Definition',
    name: 'Name',
    color: 'Color',
    note: 'Note',
    numOfTB: 'Number of time blocks',
    actions: 'Actions',
    numOfTrackings: 'Number of tracking segments',
    general: 'General',
    timeBlockes: 'Time Blockes',
    isExpectedId: 'Expected in',
    dayDefinitions: 'Day Definitions',
    noTrackingSegments: 'No Trancking Segments',
    addTrackingSegment: 'Add Tracking Segmnet',
    selectTrakingSegment: 'Please Select Tracking Segmnet',
    trackingSegment: 'Trancking Segment',
    trackingItem: 'Tracking Item',
    timeBlocksOf: 'Time Block of ',
    addTimeBlockFor: 'Add Time Block For ',
    timeblocks: 'Time Blocks',
    timeBlockType: 'Type',
    timeBlockTypes: {
      WORK: 'Work',
      BREAK: 'Break',
      ACCESS: 'Access',
    },
    isFlexTime: 'Flex Time',
    requirePunch: 'Require Punch',
    minBreakinMin: 'Minium break (min)',
    minAttendance: 'Minium Attendance (min)',
    roundingRule: 'Rounding Role',
    defaultTrackingSegemnet: 'Default Tracking Segment',
    pd: '(Previous Day)',
    overlapWithPreviousTimeBlock: 'Has overlap with previous time block',
    requirePunchEnum: {
      IN_OUT: 'In Out',
      IN: 'In',
      OUT: 'Out',
      AUTO: 'Auto',
      ANY: 'Any',
      NONE: 'None',
    },
  },
  profileFormFields: {
    preferredDateFormat: 'Preferred Date Format',
    field: 'Field',
    group: 'Group',
    payItem: 'Pay Item',
    payRate: 'Pay Rate',
    training: 'Training',
    trackingSegment: 'Tracking Segment',
    holidayCalendar: 'Holiday Calendar',
    profile: 'Profile',
    template: 'Template',
    updated: 'Updated',
    previous: 'Previous',
    firstName: 'First Name',
    lastName: 'Last Name',
    middleName: 'Middle Name',
    nickName: 'Nick Name',
    jobTitle: 'Job Title',
    employeeCode: 'Employee Code',
    emails: 'Emails',
    badgeNumber: 'Badge Number',
    tempBadgeNumber: 'Temporary Badge Number',
    seniorityDate: 'Seniority Date',
    seniorityDate2: 'Secondary Seniority Date',
    initiationDate: 'Initiation Date',
    miscDate: 'Misc Date',
    isProfileLocked: 'Is Profile Locked',
    hasAccess: 'Has Access',
    birthDate: 'Birth Date',
    maritalStatus: 'Marital Status',
    medicalAlert: 'Medical Alert',
    highestLevelEducation: 'Highest Level of Education',
    graduation: 'Graduation',
    eEDG: 'eEDG',
    band: 'Band',
    nOC: 'NOC',
    isNonResident: 'Is Non-Resident',
    citizenship: 'Citizenship',
    criminalCheck: 'Criminal Check',
    paymentMethod: 'Payment Method',
    stdHourPerDay: 'Standard Hours Per Day',
    stdHourPerPay: 'Standard Hours Per Pay',
    excludeAttendanceHoursFromPay: 'Exclude Attendance Hours From Pay',
    secondaryPayRate: 'Secondary Pay Rate',
    previousEmployment: 'Previous Employment',
    templateId: 'Template Id',
    availabilityStatus: 'Availability Status',
    canAccessDocuments: 'Can Access Documents',
    canAccessMyAvailability: 'Can Access My Availability',
    canAccessTimeEntry: 'Can Access Time Entry',
    canAccessTimeOff: 'Can Access Time Off',
    canAccssReimbursement: 'Can Access Reimbursement',
    canChangeBankAccount: 'Can Change Bank Account',
    canChangeProfile: 'Can Change Profile',
    canLogin: 'Can Login',
    federalTaxForm: 'Federal Tax Form',
    fullName: 'Full Name',
    gender: 'Gender',
    isActivePreEmp: 'Active',
    preferredTimeFormat: 'Preferred Time Format',
    preferredLanguage: 'Preferred Language',
    recordType: 'Record Type',
    taxMethodForBonus: 'Tax Method for Bonus',
    id: 'Profile ID',
    assigned: 'Assigned',
    unassigned: 'Not Assigned',
  },
  phoneInput: {
    ext: 'Ext',
    private: 'Keep Confidential',
    phoneNote: 'Phone Note',
  },
  clone: {
    cloneFromTemplate: 'Clone from Template',
    cloneFromProfile: 'Clone from Profile',
    clonefrom: 'Clone From',
  },
  organizationChart: {
    openPosition: 'Open Position',
  },
  fullEnums: {
    USD: 'USD',
    CAD: 'CAD',
    EUR: 'EUR',
    GBP: 'GBP',
    AUD: 'AUD',
    CNY: 'CNY',
    JPY: 'JPY',
    KRW: 'KRW',
    RUB: 'RUB',
    SGD: 'SGD',
    THB: 'THB',
    VND: 'VND',
    EMPLOYEE: 'Employee',
    EMPLOYEE_TEMPLATE: 'Employee Template',
    PAYEE: 'Payee',
    APPLICANT: 'Applicant',
    CANDIDATE: 'Candidate',
    CUSTOMER: 'Customer',
    QUARTERLY: 'Quarterly',
    MONTHLY: 'Monthly',
    SEMI_MONTHLY: 'Semi-Monthly',
    WEEKLY: 'Weekly',
    NONE: 'None',
    IRRELEVANT: 'Irrelevant',
    POOR: 'Poor',
    BELOW_AVERAGE: 'Below Average',
    AVERAGE: 'Average',
    GOOD: 'Good',
    EXCELLENT: 'Excellent',
    PENDING1: 'Pending 1',
    PENDING2: 'Pending 2',
    APPROVED: 'Approved',
    REJECTED: 'Rejected',
    FULL_TIME: 'Full Time',
    PART_TIME: 'Part Time',
    CASUAL: 'Casual',
    CONTRACT: 'Contract',
    STUDENT: 'Student',
    LOA: 'Leave Of Absence',
    LTD: 'Long Term Leave',
    STD: 'Short Term Leave',
    TEMP_LAID_OFF: 'Temporary Laid Off',
    ONBOARD: 'Onboard',
    TERMINATED: 'Terminated',
    RETIREE: 'Retiree',
    SALARY: 'Salary',
    HOURLY: 'Hourly',
    OTHER: 'Other',
    PICTURE: 'Picture',
    BENEFIT: 'Benefit',
    DEPARTMENT: 'Department',
    EMP_STATUS: 'Employee Status',
    EMP_TYPE: 'Employee Type',
    EMPLOYER: 'Employer',
    LICENSE: 'License',
    PAYGROUP: 'Pay Group',
    SKILL: 'Skill',
    TEAM: 'Team',
    POLICY: 'Policy',
    WORKPLAN: 'Workplan',
    LOCATION: 'Location',
    UNION: 'Union',
    PAY_CALENDAR: 'Pay Calendar',
    HOLIDAY_CALENDAR: 'Holiday Calendar',
    POSITION: 'Position',
    PERCENTAGE: 'Percentage',
    LIST: 'List',
    AVAILABLE: 'Available',
    OUT_OF_OFFICE: 'Out of Office',
    IN_A_MEETING: 'In a Meeting',
    AWAY: 'Away',
    BUSY: 'Busy',
    DO_NOT_DISTURB: 'Do Not Disturb',
    BE_RIGHT_BACK: 'Be Right Back',
    OFFLINE: 'Offline',
    SAFETY: 'Safety',
    DISCIPLINARY_ACTIONS: 'Disciplinary Actions',
    AWARDS: 'Awards',
    PHONE_CONVERSATION: 'Phone Conversation',
    MEETING: 'Meeting',
    FEDERAL: 'Federal',
    QC: 'Quebec',
    CA: 'Canada',
    US: 'USA',
    'en-US': 'en-US',
    'fr-CA': 'fr-CA',
    'he-IL': 'he-IL',
    AVATAR: 'AVATAR',
    T4: 'Tax form T4',
    R1: 'Tax form REL-1',
    ES: 'Earning Statement',
    T4A: 'Tax form T4A',
    STUB: 'Pay Stub',
    TAXFORM: 'Tax Form',
    BADGE_PICTURE: 'Badge Picture',
    CHEQUE: 'Cheque',
    LOGO: 'Logo',
    CV: 'Cirriculum Vitae',
    COVER_LETTER: 'Cover Letter',
    GROUP: 'Group',
    ASSIGNED: 'Assigned',
    ASSET: 'Asset',
    ASSET_IMAGE: 'Asset Image',
    ASSET_ASSIGNMNET: 'Asset Assignment',
    DIGITAL_ID: 'Digital ID',
    PERFORMANCE_REVIEW: 'Performance Review',
    TRAINING: 'Training',
    TRAINING_ASSIGNMNET: 'Training Assignment',
    EMPLOYER_LOGO: 'Employer Logo',
    PENDING: 'Pending',
    IN_REVIEW: 'In Review',
    SCHEDULED: 'Scheduled',
    INTERVIEWED: 'Interviewed',
    EVALUATED: 'Evaluated',
    ACCEPTED: 'Accepted',
    COMPLETED: 'Completed',
    NA: 'N/A',
    ACTIVATE_PROFILE: 'Activate Profile',
    DEACTIVATE_PROFILE: 'Deactivate Profile',
    EMP_STATUS_FULL_TIME: 'Full Time',
    EMP_STATUS_PART_TIME: 'Part Time',
    EMP_STATUS_CASUAL: 'Casual',
    EMP_STATUS_CONTRACT: 'Contract',
    EMP_STATUS_STUDENT: 'Student',
    EMP_STATUS_ONBOARD: 'Onboard',
    EMP_STATUS_TERMINATED: 'Terminated',
    EMP_RECORD_CANDIDATE: 'Candidate',
    NOTIFY_EMP: 'Notify Employee',
    NOTIFY_SUPERVISOR: 'Notify Supervisor',
    NOTIFY_HR_MANAGER: 'Notify HR Manager',
    NOTIFY_PAY_MANAGER: 'Notify Pay Manager',
    NOTIFY_CONTACT1: 'Notify Contact 1',
    NOTIFY_CONTACT2: 'Notify Contact 2',
    RESET: 'Reset',
    PROFILES: 'Profiles',
    TIMEOFFREQUESTS: 'Time Off Requests',
    ONBOARDING: 'Onboarding',
    TIMEOFF: 'Time Off',
    TIMESHEET: 'Timesheet',
    PAYROLL: 'Payroll',
    SUPPORT: 'Support',
    EMAIL: 'Email',
    SMS: 'SMS',
    PUSH: 'Push',
    INVITATION: 'Invitation',
    HIRE: 'Hire',
    EMPLOYEE_WELCOME: 'Employee Welcome',
    EMAIL_TO_EMPLOYEE: 'Email to Employee',
    PRIMARY: 'Primary',
    SECONDARY: 'Secondary',
    COLLEGE: 'College',
    TRADE_SCHOOL: 'Trade School',
    BACHELOR: 'Bachelor',
    MASTER: 'Master',
    PHD: 'PhD',
    IN_PROGRESS: 'In Progress',
    CANCELLED: 'Cancelled',
    ON_HOLD: 'On Hold',
    FOLLOW_UP: 'Follow Up',
    MALE: 'Male',
    FEMALE: 'Female',
    UNKNOWN: 'Unknown',
    MARRIED: 'Married',
    SINGLE: 'Single',
    SINGLE_PARENT: 'Single Parent',
    SIN: 'SIN',
    SSN: 'SSN',
    ID: 'ID',
    DIRECT_DEPOSIT: 'Direct Deposit',
    PAY_CHEQUE: 'Pay Cheque',
    RESCHEDULED: 'Rescheduled',
    FIXED_AMOUNT: 'Fixed Amount',
    BALANCE: 'Balance',
    START: 'Start',
    PERIODIC: 'Periodic',
    NON_PERIODIC: 'Non Periodic',
    EXEMPT: 'Exempt',
    STATUS_INDIAN: 'Indian',
    ESTIMATED_RATE: 'Estimated Rate',
    FIXED_RATE: 'Fixed Rate',
    USER: 'User',
    SYSTEM_ADMIN: 'System Admin',
    THIRD_PARTY: 'Third Party',
    SYS_ADMIN: 'Sys Admin',
    ORG_GROUP_ADMIN: 'Org Group Admin',
    ORG_ADMIN: 'Org Admin',
    HR_MANAGER: 'HR Manager',
    SUPERVISOR: 'Supervisor',
    PAY_MANAGER: 'Pay Manager',
    MANAGER: 'Manager',
    H: 'H',
    R: 'R',
    RW: 'RW',
    N: 'N',
    L1: 'L1',
    L2: 'L2',
    A: 'A',
    On: 'On',
    Off: 'Off',
    I: 'I',
    OnOff: 'OnOff',
    Y: 'Y',
    FINGERPRINT: 'Fingerprint',
    FACE_RECOGNITION: 'Face Recognition',
    FINGER_GEOMETRY: 'Finger Geometry',
    IRIS: 'Iris',
    DRAFT: 'Draft',
    POSTED: 'Posted',
    FIXED_WORK: 'Fixed Work',
    FIX_EARNED: 'Fix Earned',
    COST_PLUS_FEE: 'Cost Plus Fee',
    COST_PLUS_PERCENTAGE: 'Cost Plus Percentage',
    TIME_BANK: 'Time Bank',
    BIWEEKLY: 'Biweekly',
    FOUR_WEEKS: 'Four Weeks',
    FAMILY: 'Family',
    LIABILITY: 'Liability',
    EXPENSE: 'Expense',
    FAX: 'Fax',
    WEBSITE: 'Website',
    FACEBOOK: 'Facebook',
    LINKEDIN: 'LinkedIn',
    INSTAGRAM: 'Instagram',
    ANNUALLY: 'Annually',
    PRE_AUTHORIZED_DEBITS: 'Pre-Authorized Debits',
    INVOICE: 'Invoice',
    WORK: 'Work',
    BREAK: 'Break',
    ACCESS: 'Access',
    IN_OUT: 'In/Out',
    IN: 'In',
    OUT: 'Out',
    AUTO: 'Auto',
    ANY: 'Any',
    REJECTED1: 'Rejected',
    REJECTED2: 'Rejected',
    ADDRESS: 'Address',
    COORDINATES: 'Coordinates',
    true: 'Yes',
    false: 'No',
  },
}

export default messages
