const messages = {
  'topBar.actions': 'Actes',
  'topBar.status': 'Statut',
  'topBar.profileMenu.hello': 'Bonjour',
  'topBar.profileMenu.billingPlan': 'Plan de facturation',
  'topBar.profileMenu.role': 'Rôle',
  'topBar.profileMenu.email': 'Email',
  'topBar.profileMenu.phone': 'Téléphone',
  'topBar.profileMenu.editProfile': 'Editer le profil',
  'topBar.profileMenu.changePassword': 'Changer le mot de passe',
  'topBar.profileMenu.logout': 'Se déconnecter',
  gender: {
    MALE: 'Mâle',
    FEMALE: 'Femelle',
    OTHER: 'Autre',
  },
  pushNotification: {
    EMAIL: 'Courriel',
    SMS: 'SMS',
    PUSH: 'Notification poussée',
  },
  paymentMethod: {
    DIRECT_DEPOSIT: 'Dépôt direct',
    PAY_CHEQUE: 'Fiche de salaire',
    OTHER: 'Autre',
  },
  onlineStatus: {
    AVAILABLE: 'Disponible',
    OUT_OF_OFFICE: 'Absent du bureau',
    IN_A_MEETING: 'Dans une réunion',
    AWAY: 'Au loin',
    BUSY: 'Occupé',
    DO_NOT_DISTURB: 'Ne pas déranger',
    BE_RIGHT_BACK: 'Revenir tout de suite',
    OFFLINE: 'Hors ligne',
  },
  modalTitles: {
    assignPosition: 'Assigner une position',
    assignStatus: 'Assigner un statut',
  },
  relationStatus: {
    MARRIED: 'Mariée / Marié',
    SINGLE: 'Célibataire',
    SINGLE_PARENT: 'Célibataire avec enfant',
    UNKNOWN: 'Inconnu',
    OTHER: 'Autre',
  },
  paymentType: {
    HOURLY: 'Heure',
    SALARY: 'Salaire',
    OTHER: 'Autre',
  },
  statusEnum: {
    PENDING1: 'En attendant 1',
    PENDING2: 'En attendant 2',
    APPROVED: 'Approuvé',
    REJECTED: 'Rejeté',
  },
  degree: {
    BACHELOR: 'Baccalauréat',
    COLLEGE: 'Collège',
    MASTER: 'Master',
    PHD: 'Doctorat',
    PRIMARY: 'Primaire',
    SECONDARY: 'Secondaire',
    TRADE_SCHOOL: 'Collège',
  },
  general: {
    reset: 'Réinitialiser',
    areYouSure: 'Es-tu sûr?',
    yes: 'Oui',
    no: 'Non',
    selectGroupType: 'Sélectionnez le type de groupe',
    filterByGroup: 'Filtrer par groupe',
    years: 'ans',
    duedate: "Date d'échéance",
    issueDate: "Date d'émission",
    yearsOld: 'ans',
    empID: 'ID employé',
    attachments: 'Pièces jointes',
    properties: 'Propriétés',
    type: 'Type',
    employmentType: "Type d'emploi",
    employer: 'Employeur',
    active: 'Actif',
    empStatus: "Statut de l'employé",
    effectiveDate: "Date d'effet",
    expiryDate: "Date d'expiration",
    approvedOn: 'Approuvé le',
    approvedBy: 'Approuvé par',
    asof: 'à',
    general: 'Général',
    position: 'Position',
    additionalproperties: 'Propriétés additionnelles',
    ok: 'Ok',
    order: 'Ordre',
    actions: 'Actions',
    allemp: 'Tous les employés',
    delete: 'Supprimer',
    cancel: 'Annuler',
    bulkactions: 'Actions groupées',
    bulkdelete: 'Supprimer groupées',
    invalidvalueerror: 'Valeur invalide',
    duplicatenameerror: 'Nom déjà existant',
    home: 'Accueil',
    dataadded: 'Ajouté',
    datadeleted: 'Supprimé',
    dataupdated: 'Mis à jour',
    Compensation: 'Compensation',
    reloadpage: 'Rechargez',
    noData: 'Aucune donnée',
    success: 'Succès',
    confirmdelete: 'Êtes-vous sûr de vouloir supprimer?',
    failed: 'Échec',
    servererror: 'Erreur du serveur. Veuillez réessayer',
    somethingwentwrong: "Quelque chose s'est mal passé",
    deleted: 'Supprimé',
    informationadded: 'Information ajoutée',
    informationupdated: 'Information mise à jour',
    informationdeleted: 'Information supprimée',
    days: 'Jours',
    months: 'Mois',
    weeks: 'Semaines',
    period: 'Périod',
    details: 'Détails',
    conditions: 'Conditions',
    status: 'Statut',
    name: 'Nom',
    back: 'Retour',
    nofieldsaremodified: 'Aucun champ modifié',
    info: 'Info',
    thisactionwilleffectassignedemployeesaswell: 'Cette action affectera également les employés',
    payitemassignmentstatuswillbeupdatedforallassignedemployees:
      "Le statut de l'affectation de l'élément de paiement sera mis à jour pour tous les employés affectés",
    trackingitemsforthissegmentwillberemoved:
      'Les éléments de suivi pour ce segment seront supprimés',
  },
  editProfile: {
    personalTab1: 'Email, téléphone, date de naissance et plus',
    personalTab2: 'Adresse, code postal, code pays',
    personalTab3: 'Nom de la banque, numéro de compte, numéro de routage',
    personalTab4: 'École, diplôme, spécialité, GPA, année de graduation',
    personalTab5: "Type d'identification, numéro, date d'expiration",
    personalTab6: 'Autres paramètres',
    nonResident: 'Non-résident',
    organizationProperties: "Propriétés de l'organisation",
    bankAccounts: 'Comptes bancaires',
    idNumbers: 'Autres identifiants',
    other: 'Autres',
    level: 'Niveau',
    step: 'Étape',
    primary: 'Primaire',
    editProfile: 'Editer le profil',
    benefitplan: 'Plan de bénéfice',
    medicalAlert: 'Alerte médicale',
    addBenefitPlan: 'Ajouter un plan de bénéfice',
    assets: {
      assets: 'Actifs',
      returndate: 'Date de retour',
      assignasset: 'Affecter un actif',
      assignedassets: 'Actifs affectés',
      overdue: 'en retard',
    },
    training: {
      training: 'Formation',
      addNewTraining: 'Ajouter une formation',
      status: 'Statut',
      completionDate: 'Date de complétion',
      evaluation: 'Évaluation',
      signId: 'Signature',
      note: 'Remarque',
    },
    union: {
      union: 'Union',
      addUnion: 'Ajouter une union',
    },
    skills: {
      skills: 'Compétences',
      proficiency: 'Proficience',
      experienceinyears: 'Expérience en années',
      experienceasofdate: 'Expérience comme date d’expiration',
    },
    licenseAndPermit: {
      licenseAndPermit: 'Permis et licence',
      id: 'ID',
      addLicense: 'Ajouter une licence',
    },
    benefitOption: {
      benefitOption: 'Option de bénéfice',
      idNumber: 'ID',
      class: 'Classe',
      benefitStatus: 'Statut de bénéfice',
      claim: 'Réclamation des dépendants',
      overrideannualearnings: 'Annualisation de bénéfice',
      overridedefaultcoverage: 'Couverture de bénéfice par défaut',
      optoutmedical: 'Se retirer médical',
      optoutdental: 'Se retirer dentaire',
      optoutadnd: 'Se retirer AD&D',
      optoutclinicalillness: 'Se retirer maladie critique',
      smoker: 'Fumeur',
      evidence: 'Preuve',
      memberDescription: 'Description du membre',
    },
    benefitTableData: {
      memberDescription: 'Description du membre',
      name: 'Nom',
      option: 'Option',
      ID: 'ID',
      class: 'Classe',
      status: 'Statut',
      expiry: 'Expiré',
    },
    unionTableData: {
      expiry: 'Expiré',
      name: 'Nom',
      category: 'Catégorie',
      ID: 'ID',
      region: 'Région',
      sector: 'Secteur',
      tradeCode: 'Code du commerce',
      trade: 'Commerce',
      unionStatus: 'Statut de l’Union',
      wage: 'Salaire',
    },
    skillsTableData: {
      proficiency: 'Proficience',
      experience: 'Expérience',
      addSkill: 'Ajouter une compétence',
    },
    taxation: {
      taxation: 'Taxation',
    },
  },
  countries: {
    CANADA: 'Canada',
    USA: "États-Unis d'Amérique",
  },
  warnings: {
    reportUse: 'Use for reposts',
    datamodified: 'Données modifiées.',
    exitwithoutsave: 'Quitter sans sauvegarder?',
  },
  provinces: {
    CANADA: {
      AB: 'Alberta',
      BC: 'Colombie Britannique',
      MB: 'Manitoba',
      NB: 'Nouveau Brunswick',
      NL: 'Terre-Neuve-et-Labrador',
      NS: 'Nouvelle-Écosse',
      NT: 'Territoires du Nord-Ouest',
      NU: 'Nunavut',
      ON: 'Ontario',
      PE: 'Île-du-Prince-Édouard',
      QC: 'Québec',
      SK: 'Saskatchewan',
      YT: 'Yukon',
    },
    USA: {
      AL: 'Alabama',
      AK: 'Alaska',
      AZ: 'Arizona',
      AR: 'Arkansas',
      CA: 'Californie',
      CO: 'Colorado',
      CT: 'Connecticut',
      DE: 'Delaware',
      DC: 'District de Columbia',
      FL: 'Floride',
      GA: 'Georgie',
      HI: 'Hawaii',
      ID: 'Idaho',
      IL: 'Illinois',
      IN: 'Indiana',
      IA: 'Iowa',
      KS: 'Kansas',
      KY: 'Kentucky',
      LA: 'Louisiane',
      ME: 'Maine',
      MD: 'Maryland',
      MA: 'Massachusetts',
      MI: 'Michigan',
      MN: 'Minnesota',
      MS: 'Mississippi',
      MO: 'Missouri',
      MT: 'Montana',
      NE: 'Nebraska',
      NV: 'Nevada',
      NH: 'New Hampshire',
      NJ: 'New Jersey',
      NM: 'Nouveau-Mexico',
      NY: 'New York',
      NC: 'North Carolina',
      ND: 'North Dakota',
      OH: 'Ohio',
      OK: 'Oklahoma',
      OR: 'Oregon',
      PA: 'Pennsylvanie',
      RI: 'Rhode Island',
      SC: 'Caroline du Sud',
      SD: 'Dakota du Sud',
      TN: 'Tennessee',
      TX: 'Texas',
      UT: 'Utah',
      VT: 'Vermont',
      VA: 'Virginie',
      WA: 'Washington',
      WV: 'Virginie-Occidentale',
      WI: 'Wisconsin',
      WY: 'Wyoming',
    },
  },
  relationships: {
    AUNT: 'Tante',
    BOYFRIEND: 'Petit ami',
    BROTHER: 'Frère',
    'BROTHER-IN-LAW': 'Beau-frère',
    CONTACT: 'Contact',
    DAUGHTER: 'Fille',
    'EX-HUSBAND': 'Ex-mari',
    'EX-WIFE': 'Ex-femme',
    FATHER: 'Père',
    'FATHER-IN-LAW': 'Beau-père',
    FIANCE: 'Fiance',
    FIANCEE: 'Fiancée',
    FRIEND: 'Ami',
    GIRLFRIEND: 'Petite amie',
    GRANDFATHER: 'Grand-père',
    GRANDMOTHER: 'Grand-mère',
    HUSBAND: 'Mari',
    MOTHER: 'Femme',
    'MOTHER-IN-LAW': 'Belle-mère',
    NEIGHBOUR: 'Voisin',
    NEPHEW: 'Neveu',
    NIECE: 'Nièce',
    PARTNER: 'Partenaire',
    RELATIVE: 'Proche',
    SISTER: 'Soeur',
    'SISTER-IN-LAW': 'Belle-soeur',
    SON: 'fils',
    SPOUSE: 'Epouse',
    'STEP-DAUGHTER': 'Demie-soeur',
    'STEP-FATHER': 'Demi-père',
    'STEP-MOTHER': 'Demie-mère',
    'STEP-SON': 'Demi-fils',
    UNCLE: 'Oncle',
    UNKNOWN: 'Inconnu',
    WIFE: 'Femme',
  },
  roles: {
    ORG_ADMIN: "Administrateur de l'organisation",
    EMPLOYEE: 'Employé',
    SUPERVISOR: 'Superviseur',
    SYS_ADMIN: 'Administrateur système',
    SUPERVISORS: 'Superviseurs',
    PAY_MANAGER: 'Gestionnaires de paie',
    HR_MANAGER: 'Responsables RH',
    MANAGERS: 'Gestionnaires',
    MANAGER: 'Gestionnaire',
  },
  groupRole: {
    SUPERVISORS: 'Attribuer un ou des superviseurs',
    PAY_MANAGER: 'Attribuer un ou plusieurs gestionnaires de paie',
    HR_MANAGER: 'Affecter un ou plusieurs responsables RH',
  },
  dashboard: {
    dashboard: 'Tableau de bord',
    editProfile: 'Editer le profil',
    employees: 'Employés',
    totalDocuments: 'compte de documents',
    teams: 'Équipes',
    attendancePolicies: 'Politiques de présence',
    workPlan: 'Plan de travail',
    latestTimeOff: 'Demandes de congé récentes ',
    latestDoc: 'Derniers Documents',
    supervisor: 'Superviseur',
    leftPanel: {
      availability: 'Disponibilité',
      code: 'Code',
      badge: 'Badge',
      cell: 'Cellulaire',
      work: 'Travail',
      email: 'Email',
      groups: 'Groupes',
      lastlogin: 'Dernière connexion',
    },
  },
  buttons: {
    add: 'Ajouter',
    update: 'Mettre à jour',
    delete: 'Supprimer',
    cancel: 'Annuler',
    save: 'Sauvegarder',
    dontSave: 'Ne pas enregistrer',
    upload: 'Télécharger',
    search: 'Rechercher',
    clear: 'Effacer',
    close: 'Fermer',
    edit: 'Editer',
    view: 'Voir',
    addNew: 'Ajouter un nouveau',
    addNewEmployee: 'Ajouter un nouvel employé',
    columns: 'Colonnes',
    assigntoemployees: 'Assigner des employés',
    modify: 'Modifier',
    export: 'Exportation',
  },
  exitModal: {
    title: 'Vous avez des changements non enregistrés.',
    description: 'Souhaitez-vous enregistrer vos modifications ?',
  },
  profile: {
    terminationId: 'ID de rupture',
    basicInfo: {
      title: 'Infos générales',
      firstName: 'Prénom',
      lastName: 'Nom de famille',
      fullName: 'Nom complet',
      workEmail: 'Adresse courriel de bureau',
      personalEmail: 'Adresse courriel personnelle',
      workPhone: 'Téléphone de bureau',
      cellPhone: 'Téléphone cellulaire',
      workcellphone: 'Téléphone de bureau et cellulaire',
      homePhone: 'Téléphone de résidence',
      badgeNumber: 'Numéro de badge',
      tempBadgeNumber: 'Numéro de badge temporaire',
      employeeCode: "Code d'employé",
      seniorityDate: "Date d'ancienneté",
      secondaryseniorityDate: "Date d'ancienneté secondaire",
      initiationDate: "Date d'initiation",
      miscDate: 'Date miscellaneous',
      terminationDate: "Date de cessation d'emploi",
      changeProfilePicture: 'Changer la photo de profil',
      groups: 'Groups',
      sin: "Numéro d'assurance sociale (NAS)",
      birthDate: 'Date de naissance',
      email: 'Adresse courriel',
      hireInvitation: 'Embaucher et envoyer une invitation par e-mail',
      hiremanually: 'Embaucher et saisir manuellement les informations sur les employés',
      jobTitle: 'Titre du poste',
      recordType: "Type d'enregistrement",
      blockAccess: "Bloquer l'accès",
      blockProfileChanges: 'Bloquer les modifications de profil',
      empTemplateId: "Modèle d'employé",
      middleName: 'Nom de famille',
      alias: 'Alias',
      nickname: 'Surnom',
      status: 'Statut',
      isRegistered: 'Inscrit',
    },
    personal: {
      personal: 'Personnel',
      idNumbers: "Numéros d'identification",
      birthday: 'Anniversaire',
      gender: 'Sexe',
      paymentMethod: 'Méthodes de payement',
      payStubs: 'Des fiches de paie',
      maritalStatus: 'État civi',
    },
    address: {
      title: 'Adresse',
      address1: 'Adresse 1',
      address2: 'Adresse 2',
      city: 'Ville',
      postalCode: 'Code postal ',
      zipCode: 'Code Zip',
      country: 'Pays',
      province: 'Province',
      state: 'État',
    },
    bankAccount: {
      title: 'Compte bancaire',
      branch: 'Numéro de transit (5)',
      bank: "Numéro d'institution (3)",
      accountNumber: 'Numéro de compte (7+)',
      chequeSpecimen: 'Spécimen de chèque',
    },
    paymentMethod: {
      title: 'Méthode de paiement',
    },
    education: {
      title: 'Education',
      highestlevelofEducation: 'Niveau de formation',
      graduationDate: 'Date de graduation',
      country: 'Pays',
      notes: 'Remarques',
    },
    idNumbers: {
      idType: "Type d'identification",
      idNumber: "Numéro d'identification",
      issuedCountry: "Pays d'émission",
    },
    nonResident: {
      title: 'Non-résident',
      alertDate: "Date d'alerte",
      visaExpiryDate: "Date d'expiration du visa",
      passportExpiryDate: "Date d'expiration du passeport",
      statusReviewDate: 'Date de relecture du statut',
      passportNumber: 'Numéro de passeport',
      passportIssuingCountry: "Pays d'émission du passeport",
      status: 'Statut',
      visaNumber: 'Numéro de visa',
      visaType: 'Type de visa',
      note: 'Remarque',
    },
    preferences: {
      employeeBirthDay: "Anniversaire de l'employé",
      newDocument: 'Nouveau document',
      newSchedule: 'Nouvelle planification',
      shiftEnd: 'Fin du changement',
      shiftStart: 'Début du changement',
      timeOffApproval: 'Approbation de congé',
      timeOffComment: 'Commentaire de congé',
      timeOffRejection: 'Rejet de congé',
      timeOffSubmittal: 'Soumission de congé',
      timeSheetApproval: 'Approbation de feuille de temps',
      timeSheetComment: 'Commentaire de feuille de temps',
      timeSheetRejection: 'Rejet de feuille de temps',
      timeSheetSubmittal: 'Soumission de feuille de temps',
    },
    custom: {
      title: 'Custom',
    },
    contacts: {
      title: 'Contacts',
      contactsAndFamily: 'Contacts et famille',
      contact: 'Contact',
      relationship: 'Relation',
      callSequence: "Séquence d'appel d'urgence",
      note: 'Remarque',
    },
    settings: {
      title: 'Paramètres',
      preferences: 'Préférences',
      preferredLanguage: 'Langue préférée',
      preferredDateFormat: 'Format de date préféré',
      notifications: 'Notifications',
      isTimeSheetApproval: 'Feuille de temps approuvée',
      isTimeSheetRejection: 'Feuille de temps rejetée',
      isTimeSheetMessage: 'Message de feuille de temps',
      isTimeOffApproval: 'Congé approuvé',
      isTimeOffRejection: 'Congé rejeté',
      isNewDocument: 'Nouveau document',
      asOfDate: 'En date du :',
    },
    payRate: {
      payRateAssign: 'Assigner un taux de paye',
      addPayRate: 'Ajouter un taux de paye',
      editPayRate: 'Modifier le taux de paye',
      payRateType: 'Type de taux de paye',
      payRate: 'Taux de paye',
      currency: 'Devise',
      paymentMethod: 'Méthode de payement',
      latestEffectiveDate: "Date d'effet",
    },
    compensation: {
      standardhoursperday: 'Heures standards par jour',
      standardhoursperpay: 'Heures standards par paye',
      excludeattendancehoursfrompay: 'Exclure les heures de présence de la paye',
      secondaryPayRate: 'Taux de paye secondaire',
      prevEmployment: 'Emploi précédent',
    },
    list: {
      bulkActions: 'Actions en vrac',
      hire: 'Embaucher',
      sendEmail: 'Envoyer un e-mail',
      assignEmployeeToTheGroup: 'Affecter un employé au groupe',
      blockAccess: "Bloquer l'accès",
      activeAccess: 'Accès actif',
      empsSelected: 'employé(s) sélectionné(s).',
      effectiveDate: "Date d'effet",
      expiryDate: "Date d'expiration",
      dateBasedGroups: 'Groupes basés sur la date',
      noExpiry: 'Aucune expiration',
      filters: 'Filtres',
      resetColumns: 'Réinitialiser les colonnes',
    },
  },
  audit: {
    property: 'propriété',
    path: 'chemin',
    action: 'Action',
    date: 'Date',
    time: 'Temps',
    user: 'Utilisateur',
    from: 'De',
    to: 'À',
    batch: 'Lot',
  },
  events: {
    addEvent: 'Ajouter un événement',
    name: 'Nom',
    status: 'Statut',
    date: 'Date',
    location: 'Emplacement',
    note: 'Remarque',
    hasRSVP: 'Avec RSVP',
    statusEnum: {
      PENDING: 'En attente',
      APPROVED: 'Approuvé',
      CANCELLED: 'Annulé',
      RESCHEDULED: 'Réordonné',
    },
    isPublic: 'Public',
  },
  glaccounts: {
    addaccount: 'Ajouter un compte',
    accountNumber: 'Numéro de compte',
    glType: 'Type de compte',
    glEnum: {
      ASSET: 'Actif',
      EXPENSE: 'Dépense',
      LIABILITY: 'Passif',
    },
    status: 'Statut',
  },
  projects: {
    projects: 'Projets',
    addProject: 'Ajouter un projet',
    completed: 'Terminé',
    leader: 'Chef de projet',
    barCode: 'Code à barres',
    qrCode: 'Code QR',
    exportLink: "Lien d'exportation",
    importLink: "Lien d'importation",
    status: 'Statut',
    estimatedHours: 'Heures estimées',
    esitmatedCost: 'Coût estimé',
    note: 'Remarque',
    completedPercent: 'Pourcentage terminé',
    timeBilling: 'Facturation de temps',
    workflowState: 'Etat de flux de travail',
    changedBy: 'Modifié par',
    changedOn: 'Modifié le',
    billingRate: 'Taux de facturation',
    customerId: 'Identifiant du client',
    billingRateEnum: {
      FIXED_WORK: 'Travail fixe',
      FIX_EARNED: 'Travail fixe gagné',
      COST_PLUS_FEE: 'Coût + frais',
      COST_PLUS_PERCENTAGE: 'Coût + pourcentage',
      TIME_BANK: 'Banque de temps',
    },
    prjStatus: {
      IN_PROGRESS: 'En cours',
      ON_HOLD: 'En attente',
      CANCELLED: 'Annulé',
      COMPLETED: 'Terminé',
    },
  },
  documents: {
    action: 'Action',
    date: 'Date',
    referenceNumber: 'Numéro de réference',
    fileName: 'nom de fichier',
    description: 'La description',
    confirmdelete: 'Êtes-vous sûr de vouloir supprimer ce document?',
    note: 'Remarque',
    referenceDate: 'Date de référence',
    documentuploadedsuccess: 'Document téléchargé avec succès',
    documentuploadedfailed: 'Échec du téléchargement du document',
    documentdeletesuccess: 'Document supprimé avec succès',
    documentdeletefailed: 'Échec de la suppression du document',
    clickordragfiletothisareatoupload:
      'Cliquez ou faites glisser le fichier à cet emplacement pour télécharger',
    youcanuploadonlyonefileperupload: 'Vous pouvez télécharger un seul fichier par téléchargement',
  },
  availability: {
    addEvent: 'Ajouter un événement',
    UpdateorDeleteEvent: 'Mettre à jour ou supprimer',
    StartToEnd: 'Du début à la fin',
    date: 'Date',
    addBtn: 'Sauvegarder',
    updateBtn: 'Mettre à jour',
    delBtn: 'Supprimer',
    weekends: 'Fins de semaine',
    pickdate: 'Choisir une date',
    refresh: 'Rafraîchir',
    available: 'Disponible',
    duration: 'Durée',
  },
  payitemsOrgPage: {
    filteroptions: 'Options de filtre',
    empstatus: "Statut d'employé",
    showactiveemponly: 'Afficher uniquement les employés actifs',
    empcode: "Code d'employé",
    hourly: 'Heure',
    other: 'Autre',
    piecework: 'Pour le travail',
    payitemstatus: 'Statut',
    stuborder: 'Commande',
    manual: 'Manuel',
    payitemsOrgPage: 'Éléments payants',
    isExcludeFromPayroll: 'Exclure de la paie',
    payroll: 'Paie',
    otheramount: 'Autre montant',
    shortcut: 'Raccourci',
    payitemalreadyexists: 'Le poste de travail existe déjà',
    active: 'Actif',
    inactive: 'Inactif',
    exempt: 'Exempt',
    importlinkcode: 'Importer le code',
    exportlinkcode: 'Exporter le code',
    time: 'Temps',
    doubletime: 'Double temps',
    othertime: 'Autre temps',
    timeoff: 'Congé',
    vacation: 'Vacances',
    statutoryholiday: 'Vacances fériées',
    break: 'Pause',
    regulartime: 'Temps régulier',
    expense: 'Dépense',
    absence: 'Absence',
    work: 'Travail',
    memos: 'Mémos',
    accruals: 'Accruals',
    reimbursements: 'Remboursements',
    employerContributions: 'Contributions employeur',
    deductions: 'Deductions',
    earnings: 'Revenus',
    entrymethod: 'Méthode d’entrée',
    entryType: 'Type d’entrée',
    category: 'Catégorie',
    reportingcode: 'Code de reporting',
    assignedpayitems: 'Payitems assignés',
    editpayitem: 'Modifier le type de paiement',
    balance: 'Solde',
    rate: 'Taux',
    name: 'Nom',
    add: 'Ajouter',
    save: 'Sauvegarder',
    close: 'Fermer',
    status: 'Statut',
    description: 'Description',
    type: 'Type',
    overtime: 'Temps supp. admissible',
    contribute: 'Contribue aux congés',
    chargeable: 'Imputable',
    paidfrombank: 'Payé de banque',
    paidfromamountbank: 'Payé de banque',
    paidfromtimebank: 'Payé de banque',
    showbalance: 'Bloquer l’affichage du solde',
    displayorder: "Ordre d'affichage",
    yes: 'Oui',
    no: 'Non',
    attendancecat: 'Rubrique d’assiduité défaut',
    assigntogroups: 'Assigner aux Groupes',
    payitems: 'Items de Paie',
    payitem: 'Item de Paie',
    employees: 'Employés',
    notes: 'Commentaires',
    Available: 'Disponible',
    Selected: 'Sélectionné',
    enterdescription: 'Description d’Items de Paie',
    selectvalue: 'Sélectionnez une valeur',
    selectattendance: 'Sélectionner rubrique d’assiduité',
    addpayitem: 'Ajouter un Item de Paie',
    updatepayitem: 'Item de Paie',
    payitemdeleted: 'Item de Paie supprimé',
    payitemadded: 'Item de Paie ajouté',
    payitemupdated: 'Item de Paie mis à jour',
    payitemassignedtogroups: 'Item de Paie assigné aux Groupes',
    payitemassignedtoemployees: 'Item de Paie assigné aux Employés',
    payitemunassignedfromemployees: 'Item de Paie dé-assigné des Employés',
    assignpayitem: 'Assigner un Item de Paie',
    unassignpayitem: 'Dé-assigner un Item de Paie',
    updateassignedpayitem: 'Mettre à jour un Item de Paie assigné',
    selectpayitemstoadd: 'Sélectionnez les Items de Paie à ajouter',
  },
  payitemsGroupPage: {
    namealreadyexists: 'Nom déjà existant',
    codealreadyexists: 'Code existe déjà',
    systemNotes: 'Notes système',
    note: 'Remarque',
    code: 'Code',
    isactive: 'Actif',
    issystem: 'System',
    isReportUse: 'Utiliser pour les rapports',
    Actions: 'Actions',
    enterPayitem: 'Entrer un groupe d’Items de Paie',
    required: 'Requis',
    enterCode: 'Entrer le code',
    payitemgroup: 'Groupe d’Items de Paie',
    payitemgroups: 'Groupes d’Items de Paie',
    addpayitemgroup: 'Ajouter un groupe d’Items de Paie',
    updatepayitemgroup: 'Groupe d’Items de Paie',
    payitemgroupadded: 'Groupe d’Items de Paie ajouté',
    payitemgroupupdated: 'Groupe d’Items de Paie mis à jour',
  },
  attendancecategories: {
    attendancecategory: 'Rubrique d’assiduité',
    name: 'Nom',
    add: 'Ajouter',
    save: 'Sauvegarder',
    close: 'Fermer',
    notes: 'Remarques',
    AttendanceType: 'Type d’assiduité',
    addattendancecategory: 'Ajouter une rubrique d’assiduité',
    updateattendancecategory: 'Mettre à jour une rubrique d’assiduité',
    attendancecategorieupdated: 'Rubrique d’assiduité mise à jour',
  },
  holidayCalendar: {
    assignedholidaycalendar: 'Calendrier de vacances assigné',
    holidayCalendar: 'Calendrier des congés',
    name: 'Nom',
    namerequried: 'Nom requis',
    employees: 'Employés',
    addholidaycalendar: 'Ajouter un calendrier des congés',
    assigntoemployees: 'Assigner aux employés',
    addaholiday: 'Ajouter un congé',
    updateholiday: 'Mettre à jour un congé',
    updateholidaycalendar: 'Mettre à jour un calendrier des congés',
    updateordeleteholiday: 'Mettre à jour ou supprimer un congé',
    holidayadded: 'Congé ajouté',
    holidayupdated: 'Congé mis à jour',
    holidaydeleted: 'Congé supprimé',
    allcalendars: 'calendriers des congés',
    gotocalendar: 'Vue calendrier',
    notes: 'Remarques',
    clonecalendar: 'Copier le calendrier',
    totalholidays: 'Congés',
    importfromexistingcalendar: 'Importer depuis un calendrier existant',
    EnableConditionsforthisholiday: 'Activer les conditions pour ce congé',
    dateisrequired: 'Date requise',
  },
  holidayConditions: {
    holidayConditions: 'Conditions des congés',
    minimumSeniority: 'Ancienneté minimale',
    Employment: 'Emploie',
    holidayMustFallOnAScheduledWorkDay:
      'Le congé doit correspondre à une journée de travail cédulé',
    Employeenotabsentonthedaybeforetheholiday: 'Employé non absent le jour avant le congé',
    Employeenotabsentonthedayaftertheholiday: 'Employé non absent le jour après le congé',
    Employeenotabsentonthelastscheduledworkdaybeforetheholiday:
      'Employé non absent la dernière journée de travail cédulé avant le congé',
    Employeenotabsentonthelastscheduledworkdayaftertheholiday:
      'Employé non absent la dernière journée de travail cédulé après le congé',
    workedatleast: 'Travaillé au moins',
    daysinthelast: 'Jours dans les derniers',
    monthsbeforeholiday: 'Mois avant le congé',
    daysbeforeholiday: 'Jours avant le congé',
    calendardaysinthelast: 'Jours calendaires dans les derniers',
    Workedthatdayoftheweek: 'Travaillé le jour de la semaine',
    timesinthelast: 'fois dans les derniers',
    EmploymentshouldbeAtleast: 'L’emploi doit être au moins',
    calendardaysinthe: 'Jours calendaires dans les',
    monthspriortotheholiday: 'mois précédant le congé',
    seniority: 'Ancienneté',
    employment: 'Emploi',
    work: 'Travail',
  },
  groups: {
    groups: 'Groupes',
    name: 'Nom',
    assignedgroup: 'Groupes',
    assigngroup: 'Assigner un groupe',
    unassigngroup: 'Dé-assigner un groupe',
    confirmdelete: 'Confirmer la suppression',
    managers: 'Gestionnaires',
    create: 'Créer',
    createGroup: 'Créer un groupe',
    group: 'Grouper',
    createGroupType: 'Créer un groupe',
    wF: 'flux de travail',
    clientCode: 'Code',
    comment: 'Commenter',
    note: 'Noter',
    conflicts: 'Conflits!',
    wishToReplace: 'Souhaitez-vous remplacer ?',
    isAlreadyAssigned: 'est déjà attribué à',
    someSelectedEmployeesAreAlreadyAssigned: 'Certains employés sélectionnés sont déjà affectés.',
    createGroupFor: 'Créer un nouveau',
    updateGroupOf: 'Mettre à jour le groupe de',
    tableHeaders: {
      groupName: 'Nom de groupe',
      groupType: 'Type de groupe',
      numberOfEmployees: "Nombre d'employés",
      numberOfManagers: "Nombre d'menegers",
      primaryManager: 'Gestionnaire principal',
      primary: 'Primaire',
      actions: 'Actions',
    },
    tabs: {
      generalInfo: 'Informations générales',
      documents: 'Documents',
      properties: 'Propriétés',
      employees: 'Employés',
    },
  },
  workPlans: {
    addressLine1: 'Adresse 1',
    addressLine2: 'Adresse Ligne 2',
    searchLocation: 'Rechercher un lieu',
    alertPeriod: "Période d'alerte jours",
    alias: 'Alias',
    availabilityNumber: 'Nombre de postes disponibles',
    benefitOptions: 'Options de prestations',
    classes: 'Des classes',
    BIWEEKLY: 'Bihebdomadaire',
    businessNumberFederal: "Numéro d'entreprise fédéral",
    businessNumbers: "Numéro d'entreprise",
    businessNumberQuebec: "Numéro d'entreprise Québec",
    businessType: "Type d'entreprise",
    cCQNumber: 'Numéro CCQ',
    city: 'Ville',
    clientCode: 'Code',
    closePayWF: 'Fermer Payer',
    contact: 'Contacter',
    contactEmail: 'Email du contact',
    contactExtension: 'Extension',
    contactLanguage: 'Langue de contact',
    contactName: 'Nom du contact',
    contactPhone: 'Numéro du contact',
    coordinates: ['Latitude', 'Longitude'],
    country: 'Pays',
    currency: 'Monnaie',
    linkCode: 'Code de lien',
    internalJobListingStatus: "Statut de la liste d'emplois interne",
    thirdPartyJobListingStatus: "Statut de la liste d'emplois tiers",
    jobListingStatus: {
      open: 'Ouvrir',
      close: 'proche',
    },
    trainingIds: 'Formations',
    successionPlanWFId: 'Flux de travail du plan de relève',
    successionPlanNote: 'Note sur le plan de succession',
    eE: 'Groupe professionnel EE',
    eEO: "Catégories d'emplois EEO",
    eFTAccounts: 'Créditer des comptes bancaires',
    eIn: "Numéro d'identification de l'employeur",
    employeeRecordChangeWF: "Modification du dossier de l'employé",
    expenseWF: 'Frais',
    experienceYears: 'Expérience (années)',
    federalDepositSchedule: 'Calendrier des dépôts fédéraux',
    federalTransmitterNumber: "Numéro de l'émetteur fédéral",
    fiscalYearEndDay: "Jour de fin d'année fiscale",
    fiscalYearEndMonth: "Mois de fin d'exercice",
    FOUR_WEEKS: 'Quatre semaines',
    gLAccountID: 'Compte GL',
    hiringLeadId: 'Responsable du recrutement',
    incomeTaxForm: "Formulaire d'impôt sur le revenu",
    isActive: 'Actif',
    isAllowSchedule: "Bloquer l'affichage \"Mon horaire d'équipe\" de l'employé",
    isAllowTeamTracker: 'Bloquer l\'affichage "Mon suivi d\'équipe" des employés',
    isClosed: 'Fermé',
    isPrimary: 'Primaire',
    issuedBy: 'Délivré par',
    issuePayChequesWF: 'Émettre des chèques de paie',
    issuePayDirectDepositsWF: 'Émettre des dépôts directs',
    level: 'Niveaux',
    location: 'Emplacement',
    logo: 'Logo',
    maxSalary: 'Salaire maximal',
    memberDescription: 'Description du membre',
    minSalary: 'Salaire minimum',
    MONTHLY: 'Mensuel',
    name: 'Nom',
    qcOrFederal: 'Québec ou Fédéral',
    QC: 'Québec',
    FEDERAL: 'Fédéral',
    nameTranslate: 'Nom',
    nextSeqNumber: 'Numéro de séquence suivant',
    nOC: 'Titre de la profession CNP',
    employeeAssignmentProfile: "Propriétés d'affectation des employés",
    contactInformation: 'Coordonnées',
    ntfyPriorDays: 'Date de notification antérieure',
    ntfyTime: 'Heure de notification',
    ntfyTimeZone: 'Fuseau horaire des notifications',
    offBoardingWF: "Débarquement d'un employé",
    onBoardingWF: 'Embarquement des employés',
    pADAccounts: 'Débiter le compte bancaire',
    payCalendar: 'Calendrier de paie',
    payDate: 'Date de paiement',
    payFrequency: 'Fréquence de Paiement',
    payItems: 'Éléments payants',
    payRaiseWF: 'Augmentation de salaire',
    payrollYear: 'Année de paie',
    performanceReviewWF: 'Revue de la performance',
    periodEndDate: 'Date de fin de période',
    periodStartDate: 'Date de début de période',
    phone: 'Téléphoner',
    picture: 'Image',
    planUrl: 'URL du forfait',
    policyNumber: 'Numéro de police',
    positionApprovalWF: 'Approbation du poste',
    postalCode: 'code postal',
    zip: 'Zipper',
    posting: 'Affichage de poste',
    probationDays: 'Jours de probation',
    probationMonths: 'Mois de probation',
    proficiencies: 'Compétences',
    proficienciesList: 'Liste des compétences',
    proprietor1: 'Propriétaire 1 NAS',
    proprietor2: 'Propriétaire 2 NAS',
    providerName: 'Nom du fournisseur',
    province: 'Province',
    quebecTransmitterNumber: 'Numéro de transmetteur du Québec',
    remitFrequency: 'Fréquence de remise',
    remitFrequencyFederal: 'Fréquence de versement Fédéral',
    remitFrequencyQuebec: 'Fréquence de versement Québec',
    renewalFrequency: 'Fréquence de renouvellement mois',
    transmitterNumbers: "Numéros d'émetteur",
    transmitterNumber: "Numéro de l'émetteur",
    reportingToId: 'Faire rapport à',
    reviewFrequency: "Fréquence d'examen (mois)",
    reviewTemplate: 'Modèle de révision',
    SEMI_MONTHLY: 'Semi-mensuelle',
    sequence: 'Séquence',
    skill: 'Compétence',
    skills: 'Compétences requises',
    startDate: 'Date de début',
    step: 'Pas',
    sUITax: "Impôt d'État sur l'assurance-chômage (SUI)",
    taxWithholdingCountry: "Pays de retenue d'impôt",
    timeOffRequestWF: 'Temps libre',
    timeSheetPayrollSubmitWF: 'Soumission de la feuille de temps',
    timeSheetWF: 'Emploi du temps',
    transitNumber: 'Numéro de transit',
    WEEKLY: 'Hebdomadaire',
    workPlanPublishDate: 'Date de publication du plan de travail / Heure',
    jobDescription: "Description de l'emploi",
    stateIdNo: {
      state: "Nom d'état",
      idNumber: "Identifiant d'état",
    },
    account: {
      bank: 'Banque',
      branch: 'Une succursale',
      accountNumber: 'Numéro de compte',
    },
    proficienciesOptions: {
      irrelevant: 'Sans importance',
      poor: 'Pauvre',
      bellow: 'Mugissement',
      average: 'Moyen',
      good: 'Bien',
      excellent: 'Excellent',
      IRRELEVANT: 'Hors du sujet',
      POOR: 'Pauvres',
      BELOW: 'Ci-dessous',
      AVERAGE: 'Moyen',
      GOOD: 'Bon',
      EXCELLENT: 'Excellent',
    },
    options: {
      none: 'None',
      levelOne: 'Level 1',
      levelTwo: 'Level 2',
    },
    unionTabs: {
      unionStatuses: 'Statut syndical',
      tradeCodes: 'Codes commerciaux',
      sectors: 'Secteurs',
      categories: 'Catégories',
      regions: 'Régions',
      wages: 'Annex',
    },
  },
  groupTypes: {
    groupTypes: 'Types de groupe',
    groupTypeName: 'Nom du type de groupe',
    addressUsed: 'Adresse utilisée',
    color: 'Couleur',
    datedEmployeeAssignment: "Affectation d'employé datée",
    allowMultipleEmployeeAssignment: "Autoriser l'affectation de plusieurs employés",
    systemType: 'Type de système',
  },
  groupSystemTypes: {
    TEAM: 'Équipe',
    DEPARTMENT: 'département',
    POLICY: 'Politique',
    WORKPLAN: 'Plan de travail',
    PAYGROUP: 'Groupe de rémunération',
    SITE: 'Placer',
    UNION: 'Syndicat',
    EMP_TYPE: "Type d'emploi",
    LOCATION: 'lieu',
    POSITION: 'Position',
    EMP_STATUS: "Statut d'emploi",
    EMPLOYER: 'Employeur',
    PAY_CALENDAR: 'calendrier de paie',
    BENEFIT: "Régime d'avantages sociaux",
    SKILL: 'Compétence',
    LICENSE: 'Licence',
    PERMIT: 'Permis',
    OTHER: 'Autre',
  },
  supervisors: {
    organization: 'Organisation',
    profile: 'Profil',
    menuProfile: 'Profil des menus',
    isPrimarySupervisor: 'Est le superviseur principal',
    isPrimaryManager: 'Gestionnaire principal',
    createAndModifyPunches: 'Créer et modifier des poinçons',
    temporaryOnboarding: 'Intégration temporaire',
    timeSheetApproval: 'Approbation des feuilles de temps',
    timeOffRequestApproval: 'Approbation de la demande de congé',
    expenseReimbursementApproval: 'Approbation du remboursement des dépenses',
    employeeProfiles: 'Profils des employés',
    employeePayStubs: 'Bulletins de paie des employés',
    employeeTimeSheet: 'Feuille de temps des employés',
    employeeConfidentialInformation: 'Informations confidentielles sur les employés',
    employeeSchedules: 'Horaires des employés',
    employeeExpenseReimbursement: 'Remboursement des dépenses des employés',
    employeePayRates: 'Taux de rémunération des employés',
    performanceReviews: 'Évaluations des performances',
    EmployeeTimeOffRequests: 'Demandes de congés des employés',
    timeSheetSubmittal: 'Soumission des feuilles de temps',
    timeOffRequestSubmittal: 'Soumission de la demande de congé',
    expenseReimbursementSubmittal: 'Soumission de remboursement des dépenses',
    issuePayChequeApprovalLevelEnum: "Émettre l'approbation des chèques de paie",
    issuePayDirectDepositApprovalLevelEnum: "Émettre l'approbation des dépôts directs de paiement",
    accessTemplate: "Modèles d'employés",
    closePayApprovalLevelEnum: "Fermer l'approbation de la paie",
    payItems: 'Éléments payants',
    actions: 'Actions',
    onBoard: 'À bord',
    offBoard: 'Offboard',
    invite: 'Inviter',
    both: 'Tous les deux',
    onboardApproval: 'Approbation à bord',
    offboardApproval: 'Approbation externe',
    performanceApproval: 'Approbation des évaluations de performance',
    positionApproval: 'Approbation des changements de poste',
    accessPosition: 'Changement de poste',
    onboardNtfy: 'Soumission à bord',
    offboardNtfy: 'Soumission externe',
    performanceNtfy: 'Soumission des évaluations de performance',
    positionNtfy: 'Soumission de changement de poste',
    closePayNtfyLevel: 'Fermer la notification de paiement',
    issuePayDirectDepositNtfyLevel: 'Émettre le dépôt direct des paiements',
    issuePayChequeNtfyLevel: 'Émettre des chèques de paie',
    onboardOffboard: 'Embarquement / Débarquement',
    accessCalendar: 'Calendriers de paie et de vacances',
    menuTemplate: 'Modèle de menus',
    selectMenuTemplate: 'Sélectionnez un modèle de menu',
    tabs: {
      permissions: 'Autorisations',
      authorityLevel: "Niveau d'autorité",
      accessLevel: "Niveau d'accès",
      notificationLevel: 'Niveau de notification',
    },
    placeholders: {
      select: 'Sélectionner',
    },
    options: {
      none: 'Rien',
      all: 'Tout',
      hide: 'Cacher',
      view: 'Voir',
      modify: 'Modifier',
      create: 'Créer',
      delete: 'Supprimer',
      levelOne: 'Premier niveau',
      levelTwo: 'Niveau deux',
    },
  },
  modals: {
    createGroupType: 'Créer un type de groupe',
    updateGroupType: 'Update Group Type',
    createGroup: 'Create Group',
    updateGroup: 'Update Group',
    createSupervisor: 'Créer un superviseur',
  },
  form: {
    general: {
      fieldisrequired: 'Ce champ est requis',
      submit: 'Soumettre ',
      save: 'Sauvegarder',
      name: 'Nom',
      note: 'Remarque',
      clientcode: 'Code client',
      reportingcode: 'Code de reporting',
      displaysequence: 'Séquence',
      mandatory: 'Obligatoire',
      active: 'Actif',
      inactive: 'Inactif',
      geoposition: 'Position géographique',
    },
    group: {
      general: {
        name: 'Nom de groupe ',
        groupType: 'Type de groupe ',
        parentGroup: 'Groupe initial',
      },
      team: {
        expenseWF: 'Flux de dépense',
        timeSheetPayrollSubmitWF: 'Flux de soumission à la paie de feuille de temps',
        timeSheetWF: 'Flux de feuille de temps',
        timeOffRequestWF: 'Flux de demande d’absence ',
      },
      department: {
        onBoardingWF: 'Flux de décalage employé ',
        offBoardingWF: 'Flux de respect employé',
        payRaiseWF: 'Flux d’augmentation de salaire',
        positionApprovalWF: 'Flux d’approbation de poste',
        recordChangeWF: 'Flux de changement de dossier d’employé ',
      },
      paygroup: {
        closePayWF: 'Flux de clôture de paie ',
        issuePayChequesWF: 'Flux d’émission de dépôt direct de paie',
        issuePayDirectDepositsWF: 'Flux d’émission de chèques de paie',
      },
      address: {
        addressLine1: 'Address 1',
        addressLine2: 'Address 2',
        city: 'City',
        country: 'Country',
        location:
          'GPS coordinates / Choose Address ID Internet to enter or view Internet information',
        phone: 'Phone ',
        picture: 'Picture',
        postalCode: 'Zip code / Postal code',
        province: 'State / Province',
      },
    },
  },
  notification: {
    success: {
      add: 'Item Sucessfully Added',
      update: 'Item Sucessfully Updated',
      delete: 'Item Sucessfully Removed',
    },
  },
  trackingsegments: {
    assigntrackingsegment: 'Assigner un segment de suivi',
    assignedTrackingSegments: 'Segments assignés',
    displaysequence: 'Séquence d’affichage',
    trackingitemsfor: 'Les éléments de suivi pour',
    itemswillberemoved: 'Les éléments seront supprimés',
    bulkdeletetrackingitems: 'Supprimer des éléments de suivi en masse',
    viewtrackingitems: 'Voir les éléments de suivi',
    addtrackingsegment: 'Ajouter un segment de suivi',
    updatetrackingsegment: 'Segment de suivi',
    addtrackingitem: 'Ajouter un élément de suivi',
    updatetrackingitem: 'Mettre à jour un élément de suivi',
    trackingsegments: 'Segments de suivi',
    type: 'Type',
    validationlistdisplay: 'Choix d’affichage',
    validationlistdisplaytype: 'Choix d’affichage',
    validationmethod: 'Méthode de validation',
    freeform: 'Formulaire libre',
    grouptype: 'Type de groupe',
    logical: 'Logique',
    integer: 'Entier',
    numeric: 'Numérique',
    list: 'Liste',
    jira: 'Jira',
    position: 'Position',
    project: 'Projet',
    code: 'Code',
    name: 'Nom',
    both: 'Nom et code',
  },
  assets: {
    assets: 'Actifs',
    assignments: 'Missions',
    assignmentsOf: 'Missions de',
    createAsset: 'Créer un actif',
    editAsset: "Modifier l'actif",
    isActive: 'Statut',
    assetName: 'Nom',
    note: 'Noter',
    code: 'Code',
    linkCode: 'Code de lien',
    serialNo: 'Numéro de série',
    config: 'Configuration',
    vendor: 'Vendeur',
    purchaseDate: "date d'achat",
    cost: 'Coût',
    currency: 'Monnaie',
    dueDatePeriod: "Période d'alerte de la date d'échéance",
    nextScheduleDate: 'Prochaine date de maintenance planifiée',
    action: 'Action',
    contact: 'Contacter',
    contactName: 'Nom du contact',
    contactPhone: 'Numéro du contact',
    contactEmail: 'Email du contact',
    properties: 'Propriétés',
    documents: 'Documents',
    employeeAssignment: 'Affectation des employés',
    assignAssetToEmployee: "Attribuer un actif à l'employé",
    employee: 'Employé',
    issueDate: "Date d'émission",
    dueDate: "Date d'échéance",
    returnDate: 'Date de retour',
    status: 'Statut',
    onlyShowAvailableAssets: 'Afficher uniquement les ressources disponibles',
    createAssset: 'Créer un actif',
    updateAsset: "Modifier l'actif",
    createAssignment: 'Créer un devoir',
    updateAssignment: "Modifier l'affectation",
    setReturnDateToToday: "Définir la date de retour sur Aujourd'hui",
    image: 'Image',
  },
  performance: {
    list: 'Lister',
    month: 'Mois',
    week: 'La semaine',
    at: 'à',
    addPerformanceReview: 'Ajouter un examen des performances',
    editPerformanceReview: "Modifier l'évaluation des performances",
    reviewStatus: 'Statut',
    reviewDate: 'Date/heure de révision',
    period: "Période d'examen (mois)",
    duration: 'Durée (minutes)',
    evaluatorProfile: 'Évaluateur',
    employeeProfile: 'Employé',
    location: "Emplacement de l'examen",
    alertInDays: 'Alerte de révision (jours)',
    alertInMinutes: 'Alerte de révision (minutes)',
    positionGroup: 'Position',
    reviewScore: "Note d'examen",
    general: 'Général',
    scores: 'Partitions',
    performanceReviewCategory: 'Catégorie',
    score: 'Score',
    note: 'Noter',
    action: 'Action',
    evaluatorNote: 'Évaluateur',
    employeeNote: 'Employé',
    signature: 'Signature',
    reviewFor: 'Examen pour',
    reviewBy: 'Révision par',
    latestEvaluation: 'Dernière évaluation (date)',
    attachments: 'Pièces jointes',
    reviewWf: 'Réviser le flux de travail',
    wfStatus: 'État du flux de travail :',
    reviewStatuses: {
      TBD: 'À déterminer',
      WF: 'Flux de travail',
      PROPOSED: 'Proposé',
      DRAFT: 'Ébauche',
      INVITE: 'Invité',
      ACKNOWLEDGED: 'Reconnu',
      PENDING: 'En attente',
      COMPLETED: 'Terminé',
      ON_HOLD: 'En attente',
      FOLLOW_UP: 'Suivi',
    },
    training: {
      profile: 'Profil',
      sign: 'Signature',
      addAssignment: 'Ajouter une affectation',
      actions: 'Actions',
      issueDate: "Date d'émission",
      evaluation: 'Évaluation',
      dueDate: "Date d'échéance",
      fullName: 'Nom complet',
      trainingStatus: 'Statut de la formation',
      completionDate: "Date d'achèvement",
      assign: 'Attribuer',
      assignmentsOf: 'Missions de',
      addTraining: 'Ajouter une formation',
      code: 'Code',
      name: 'Nom',
      linkCode: 'Code de lien',
      status: 'Statut',
      active: 'Actif',
      note: 'Noter',
      urlList: "Liste d'URL",
      url: 'URL',
      assignedTo: 'Employés',
      general: 'Général',
      documents: 'Documents',
      recurrence: 'Récurrence (mois)',
      reqSign: 'Signatures requises',
      createTraining: 'Créer une formation',
      updateTraining: 'Mettre à jour la formation',
    },
  },
  languages: {
    EN: 'Anglais',
    FR: 'Français',
    'hr-IL': 'hébreu',
  },
  monthsInNum: {
    1: 'Janvier',
    2: 'Février',
    3: 'Mars',
    4: 'Avril',
    5: 'Mai',
    6: 'Juin',
    7: 'Juillet',
    8: 'Août',
    9: 'Septembre',
    10: 'Octobre',
    11: 'Novembre',
    12: 'Décembre',
  },
  signer: {
    clickToSign: 'Cliquez pour signer',
    removeSign: 'Supprimer la signature',
    signedOn: 'Signé le',
    signedBy: 'Signé par',
  },
  breadcrumbs: {
    home: 'Domicile',
    customers: 'Clients',
    unknownPage: 'Page inconnue',
    projects: 'Projets',
    groups: 'Groupes',
    unknownType: 'Type inconnu',
    workforce: "la main d'oeuvre",
    employeeGroups: "Groupes d'employés",
    attendance: 'Présence',
    team: 'Équipe',
    organization: 'Organisme',
    locations: 'Emplacements',
    unions: 'Les syndicats',
    advanced: 'Avancé',
    employeeTypes: "Types d'employés",
    departments: 'Départements',
    positions: 'Postes',
    benefitPlans: "Régimes d'avantages sociaux",
    licenses: 'Licence',
    skills: 'Compétences',
    pay: 'Payer',
    employers: 'Employeurs',
    payGroups: 'Groupes de paiement',
    availability: 'Disponibilité',
    trackingSegments: 'Segments de suivi',
    assets: 'Actifs',
    calendars: 'Calendriers',
    event: 'Événement',
    holidays: 'Vacances',
    employees: 'Employés',
    organizationChart: 'Organigramme',
    performance: 'Performance',
    training: 'Formation',
    items: 'Articles',
    payItems: 'Éléments payants',
    payItemGroups: "Groupes d'articles de paiement",
    workflow: 'Flux de travail',
    workflowSteps: 'Étapes du flux de travail',
    steps: 'Pas',
    workflowAssignments: 'Affectations de flux de travail',
    assignments: 'Missions',
    payees: 'Bénéficiaires',
    glaccounts: 'Comptes de comptabilité',
  },
  wF: {
    wF: 'Flux de travail',
    wFTransition: 'Transitions de flux de travail',
    transitionFrom: 'Transition de',
    noStateError: 'Veuillez ajouter au moins un état',
    status: 'Statut',
    active: 'Actif',
    name: 'Nom',
    type: 'Taper',
    actions: 'Actions',
    transitions: 'Transitions',
    steps: 'Pas',
    actionList: "Liste d'action",
    note: 'Noter',
    contacts: 'Contacts',
    general: 'Général',
    updateWF: 'Mettre à jour le flux de travail',
    addWF: 'Ajouter un flux de travail',
    contactProfileOne: 'Contacter 1',
    contactProfileTwo: 'Contactez 2',
    fromStatus: 'État du formulaire',
    toStatus: 'Au statut',
    tasks: 'Tâches',
    task: 'Tâche',
    nt: 'Modèle de notification',
    checklist: 'Liste de contrôle',
    assign: 'Attribuer',
    addTransition: 'Ajouter une transition',
    updateTransition: 'Mettre à jour la transition',
    fullName: 'Nom complet',
    profile: 'Profil',
    effectiveDate: 'Date effective',
    state: 'État',
    fromState: "De l'État",
    toState: 'Établir',
    addChecklist: 'Ajouter une liste de contrôle',
    assigned: 'Attribué!',
    unassigned: 'Non attribué!',
    moveToNextStep: "Passer à l'étape suivante",
    types: {
      ONBOARDING: 'Intégration',
      OFFBOARDING: 'Débarquement',
      REVIEW: 'Revue de la performance',
    },
    noChecklist: 'Pas de liste de contrôle !',
    noTransition: 'Pas de transition !',
    moveFrom: 'Déplacer de',
    to: 'Pour',
    setTo: 'Mis à',
    logs: 'Journaux',
    logsFor: 'Journaux pour',
    user: 'Utilisateur:',
    undoLastTransition: 'Annuler la dernière transition',
    wantToRunAction: "Voulez-vous exécuter cette action de l'état actuel à l'état précédent ?",
    yesRunActions: 'Oui, exécuter des actions',
    noDeleteLastTransition: 'Non, supprimer la dernière transition',
    actionsFiredSuccessfully: 'Actions déclenchées avec succès !',
    checklistStatuses: {
      PENDING: 'En attente',
      COMPLETED: 'Terminé',
      NA: "N'est pas applicable",
    },
    defaultStates: {
      START: 'Démarrer',
      IN_PROGRESS: 'En cours',
      CANCELLED: 'Annulé',
      REJECTED: 'Rejeté',
      ON_HOLD: 'En attente',
      FOLLOW_UP: 'Suivi',
      COMPLETED: 'Terminé',
    },
    actionsList: {
      ACTIVATE_PROFILE: 'Activer le profil',
      DEACTIVATE_PROFILE: 'Désactiver le profil',
      EMP_STATUS_PART_TIME: "Statut d'employé - Temps partiel",
      EMP_STATUS_FULL_TIME: "Statut d'employé - Temps plein",
      EMP_STATUS_CASUAL: "Statut d'employé - Occasionnel",
      EMP_STATUS_CONTRACT: "Statut d'employé - Contrat",
      EMP_STATUS_STUDENT: "Statut d'employé - Étudiant",
      EMP_STATUS_ONBOARD: "Statut d'employé - Intégration",
      EMP_STATUS_TERMINATED: "Statut d'employé - Fini",
      NOTIFY_EMP: "Aviser l'employé",
      NOTIFY_SUPERVISOR: 'Aviser le superviseur',
      NOTIFY_HR_MANAGER: 'Informer le responsable RH',
      NOTIFY_PAY_MANAGER: 'Aviser le responsable de la paie',
      NOTIFY_CONTACT1: 'Aviser le contact 1',
      NOTIFY_CONTACT2: 'Avertir le contact 2',
      RESET: 'Réinitialiser',
    },
    createWfWithTypeOnboarding:
      "Veuillez créer au moins un flux de travail avec le type d'intégration",
    noCheckList: 'Pas de liste de contrôle',
    youCanMove: 'Vous pouvez vous déplacer !',
    direction: 'Direction',
    date: 'Date',
  },
  templates: {
    general: 'Général',
    name: 'Nom',
    templateType: 'Type de modèle',
    INVITATION: 'Invitation',
    HIRE: 'Louer',
    EMPLOYEE_WELCOME: 'Bienvenue aux employés',
    EMAIL_TO_EMPLOYEE: "Courriel à l'employé",
    active: 'Actif',
    note: 'Noter',
    email: 'E-mail',
    htmlMessage: 'Message HTML',
    placeholders: 'Espaces réservés',
    clickAndPaste: 'Cliquez et collez ci-dessus',
    sms: 'SMS',
    smsMessage: 'SMS',
    pushNotification: 'Notification push',
    status: 'Statut',
    isSystem: 'Système',
    action: 'Action',
    addTemplate: 'Ajouter un modèle de notification',
    employeeFirstName: "Prénom de l'employé",
    employeeLastName: "Nom de famille de l'employé",
    supervisorFirstName: 'Prénom du superviseur',
    supervisorLastName: 'Nom de famille du superviseur',
    managerFirstName: 'Prénom du responsable',
    managerLastName: 'Nom de famille du responsable',
    date: 'Date',
    dateAsText: 'Date sous forme de texte',
    timeAmPm: 'Heure (AM/PM)',
    time24h: 'Heure (24h)',
    companyName: "Nom de l'entreprise",
    companyLogo: "Logo d'entreprise",
    copied: 'Copié !',
  },
  applicant: {
    status: 'Statut',
    jobTitle: "Titre d'emploi",
    position: 'Position',
    firstName: 'Prénom',
    lastName: 'Nom de famille',
    personalPhone: 'Téléphone personnel, cellulaire',
    personalEmail: 'Email personnel',
    cvAttachment: 'Pièce jointe au CV',
    coverLetter: 'Lettre de motivation',
    email: 'E-mail',
    fullName: 'Nom complet',
    active: 'Actif',
    progress: 'Le progrès',
    actions: 'Actions',
    general: 'Général',
    emailTemplate: "Modèle d'e-mail",
    saveAndGoTo: 'Enregistrez et accédez à',
    pleaseSelectTemplate: 'Veuillez sélectionner un modèle',
    addApplicant: 'Ajouter un candidat',
    wfId: 'Flux de travail',
    APPLICANT: 'Demandeur',
    CANDIDATE: 'Candidat',
    wfStatus: 'Statut du flux de travail',
    employer: 'Employeur',
    applicationStatus: 'État de la candidature',
    firstSave: "Veuillez d'abord enregistrer le document, puis essayez",
  },
  uploader: {
    title: 'Cliquez ou faites glisser le fichier dans cette zone pour le télécharger',
    subtitle:
      "Prise en charge d'un téléchargement unique ou groupé. Interdire strictement de télécharger des données d'entreprise ou d'autres fichiers de groupe",
    sync: 'Synchroniser les documents',
    singleTitle: 'Cliquez pour télécharger',
  },
  profileFormFields: {
    updated: 'Mis à jour',
    previous: 'Précédent',
    firstName: 'Prénom',
    lastName: 'Nom de famille',
    middleName: 'Deuxième prénom',
    nickName: 'Surnom',
    jobTitle: "Titre d'emploi",
    employeeCode: "Code de l'employé",
    emails: 'Courriels',
    badgeNumber: 'Numéro de badge',
    tempBadgeNumber: 'Numéro de badge temporaire',
    seniorityDate: 'Date de seniorité',
    seniorityDate2: 'Date de seniorité 2',
    initiationDate: "Date d'initiation",
    miscDate: 'Date de miscellaneous',
    isProfileLocked: 'Verrouiller le profil',
    hasAccess: 'Accès',
    birthDate: 'Date de naissance',
    maritalStatus: 'Statut marital',
    medicalAlert: 'Médicale',
    highestLevelEducation: "Haut niveau d'éducation",
    graduation: 'Graduation',
    eEDG: 'eEDG',
    band: 'Bande',
    nOC: 'NOC',
    isNonResident: 'Non-résident',
    citizenship: 'Citoyenneté',
    criminalCheck: 'Vérifier la criminalité',
    paymentMethod: 'Mode de paiement',
    stdHourPerDay: 'Heures par jour',
    stdHourPerPay: 'Heures par pay',
    excludeAttendanceHoursFromPay: 'Exclure les heures de présence des heures de pay',
    secondaryPayRate: 'Taux de pay secondaire',
    previousEmployment: 'Ancienneté',
  },
}

export default messages
